-- freecrypto.net — seed data dump
-- Generated by scripts/seed-to-sql.ts; regenerate with `npm run seed:sql`
-- Safe to re-run: every INSERT is idempotent via UNIQUE keys + ON DUPLICATE KEY UPDATE.
SET NAMES utf8mb4;

-- chains
INSERT INTO chains (slug, name, description, sort_order) VALUES ('ethereum', 'Ethereum', 'Original smart-contract chain. Most airdrops still anchor here for L2 retroactives.', 10) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('solana', 'Solana', 'High-throughput L1 with an active airdrop ecosystem (Jupiter, Drift, Kamino, Jito).', 20) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('base', 'Base', 'Coinbase L2 with strong consumer-app traction and no native token (yet).', 30) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('arbitrum', 'Arbitrum', 'Optimistic L2; protocols deployed here remain top airdrop hunting ground.', 40) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('optimism', 'Optimism', 'OP Stack chain with recurring Merit-based airdrop rounds.', 50) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('scroll', 'Scroll', 'zkEVM L2; protocols on it are points-heavy pre-TGE.', 60) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('linea', 'Linea', 'ConsenSys zkEVM, MetaMask-integrated, no native token announced.', 70) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('berachain', 'Berachain', 'Proof-of-Liquidity L1; testnet activity points are tracked for genesis distribution.', 80) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('monad', 'Monad', 'Parallel-EVM L1 in testnet phase; testnet usage may qualify for genesis allocation.', 90) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('sui', 'Sui', 'Move-based L1 with periodic ecosystem incentive programs.', 100) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('ton', 'TON', 'Telegram-native chain; tap-to-earn and mini-app airdrops are concentrated here.', 110) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('starknet', 'Starknet', 'Cairo-based zkRollup; protocols deployed here remain in points phase.', 120) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);

-- categories
INSERT INTO categories (slug, name, description, sort_order) VALUES ('retroactive', 'Retroactive', 'Drops that reward past on-chain activity — usually announced after a snapshot. The highest-EV category historically.', 10) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('testnet', 'Testnet', 'Active incentivized testnets where on-chain tasks accrue points convertible to a future token.', 20) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('points', 'Points', 'Live points programs (Eigen, Ether.fi, Renzo, Pendle YT etc.) where points are expected to convert to tokens.', 30) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('holder', 'Holder', 'Hold-to-earn drops: holders of a specific NFT or token at snapshot qualify automatically.', 40) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('task', 'Task-based', 'Galxe-style quest campaigns: complete on-chain or social tasks for whitelist or guaranteed allocation.', 50) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('exchange', 'Exchange', 'Centralized exchange Launchpool / Megadrop / HODLer style drops (Binance, Bybit, OKX, MEXC).', 60) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('telegram', 'Telegram', 'TON-native tap-to-earn and Telegram mini-app airdrops.', 70) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);

-- sources
INSERT INTO sources (slug, name, url) VALUES ('editorial', 'freecrypto.net editorial', 'https://freecrypto.net') ON DUPLICATE KEY UPDATE name=VALUES(name), url=VALUES(url);
INSERT INTO sources (slug, name, url) VALUES ('defillama', 'DefiLlama Airdrops', 'https://defillama.com/airdrops') ON DUPLICATE KEY UPDATE name=VALUES(name), url=VALUES(url);
INSERT INTO sources (slug, name, url) VALUES ('cryptorank', 'CryptoRank Drophunting', 'https://cryptorank.io/drophunting') ON DUPLICATE KEY UPDATE name=VALUES(name), url=VALUES(url);
INSERT INTO sources (slug, name, url) VALUES ('airdropalert', 'AirdropAlert', 'https://airdropalert.com') ON DUPLICATE KEY UPDATE name=VALUES(name), url=VALUES(url);
INSERT INTO sources (slug, name, url) VALUES ('airdropsio', 'airdrops.io', 'https://airdrops.io') ON DUPLICATE KEY UPDATE name=VALUES(name), url=VALUES(url);
INSERT INTO sources (slug, name, url) VALUES ('coinmarketcap', 'CoinMarketCap Airdrops', 'https://coinmarketcap.com/airdrop') ON DUPLICATE KEY UPDATE name=VALUES(name), url=VALUES(url);

-- airdrops + per-airdrop visit_codes + faqs
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'monad-genesis', 'Monad', 'MON', NULL, 'Highest-funded EVM L1 of the cycle ($244M from Paradigm). Public testnet live since Feb 2026. Genesis airdrop unconfirmed but extremely likely based on peer-launch precedent.',
      'Monad is the most heavily-funded EVM-compatible L1 of the 2026 cycle. The project raised **$244M** in April 2024 led by Paradigm at a $3B post-money valuation, with Coinbase Ventures, Greenoaks, Castle Island, Dragonfly, and Hudson River Trading joining. The founding team — former Jump Crypto traders Keone Hon, James Hunsaker, and Eunice Giarta — has been building since 2022 with a single product thesis: a parallel-execution EVM that targets 10,000 TPS while staying 100% bytecode-compatible with Ethereum. Every existing Solidity contract can deploy to Monad with zero code changes.

The public testnet went live on **February 19, 2026**. Within the first month, more than 4.2M unique addresses had interacted with at least one testnet dapp. The native ecosystem — Ambient (CLOB DEX), Apriori (liquid staking), Kuru (perps), Magma (lending) — launched alongside the testnet, and validator delegations crossed $850M in test-MON within six weeks. Mainnet is provisionally targeted for late 2026 or early 2027.

A genesis airdrop has not been formally announced. The team has stated publicly that ''testnet activity will be considered'' without committing to a specific allocation or formula. Every comparable launch in this funding bracket — Berachain ($142M), Eclipse, MegaETH ($30M) — said the same thing before distributing 5–15% of supply to early users. The risk-adjusted bet is that there IS an airdrop, and the open question is just the scoring formula and snapshot window.

What the team has emphasized publicly: they will aggressively filter sybils, they will weight Monad-native dapp activity higher than generic deploys, and they care about behavioral diversity over raw transaction count. That last point matters — farms that pump 1000 transactions per wallet typically score lower than wallets that look like real users with 100 thoughtful interactions.', 'Monad has not published an explicit scoring formula. Based on team statements and what comparable peers (LayerZero, Arbitrum, ZK Sync) used, expect the following inputs to matter:

**Strong positive signals:**
- Activity across 4+ distinct dapp categories (DEX, lending, NFT, governance)
- 30+ unique daily transactions spread over 60+ days
- Sustained LP or lending position held across multiple weeks
- Use of Monad-native protocols (Ambient, Apriori, Kuru) over generic deploys
- Validator delegations or governance votes
- Activity continuing AFTER any speculated snapshot — real users don''t disappear

**Strong negative signals (likely filtered out):**
- 5+ wallets funded from the same CEX address within minutes
- Identical transaction amounts across wallets, especially round numbers
- Trading exclusively between your own wallets (wash trades)
- Activity concentrated in 1–2 day bursts
- Going dark immediately after a confirmed snapshot date
- Funding from known mixer addresses or sanctioned sources

**Realistic targets:**
- **Minimum bar to qualify:** 30+ daily-unique transactions across 60+ days, 4+ dapp categories
- **Recommended bar to maximize allocation:** 60+ days of activity, $50–200 in LP/lent positions, multiple Monad-native NFT mints, validator delegations
- **Maximum recommended wallets per identity:** 3–5 with materially different behavioral profiles
- **Gas budget:** $10–50 across the campaign

The team has confirmed on-chain clustering analysis is already running. If you funded a stack of wallets from one source on the same day, your allocation is at risk before you''ve made your first swap.', '1. **Spin up a fresh wallet.** Don''t reuse a wallet that''s touched known sybil farms (Hop, OmniBTC, LayerZero residuals). New MetaMask or Rabby profile.
2. **Get test-MON from the official faucet only.** [testnet.monad.xyz/faucet](https://testnet.monad.xyz/faucet) — never any third-party ''Monad faucet'' site. Rate-limited to one request per 24 hours per wallet.
3. **Bridge testnet ETH from Sepolia.** Use the canonical bridge at bridge.monad.xyz. Bridge 3+ separate times across different days, not all at once.
4. **Trade weekly on Ambient or Kuru.** 3+ swaps per week across varied pairs (test-MON/USDC, test-USDC/USDT, test-ETH/MON). Don''t trade between your own wallets — that''s wash trading and gets you flagged.
5. **Provide liquidity for 7+ days.** Apriori liquid staking or Beethoven X LP positions both qualify. Keep the position live through any speculated snapshot window.
6. **Mint Monad-native NFTs.** Several ecosystem projects run testnet mints. Cost: 1–2 test-MON each.
7. **Vote on governance proposals.** The Monad Foundation has run mock-governance experiments. Participating is a low-cost signal of genuine interest.
8. **Continue activity post-snapshot.** When the snapshot is announced (likely 2–4 weeks pre-mainnet), don''t immediately stop. Many graders penalize cliff-stoppers.
9. **Watch only official channels.** The claim portal will go live on monad.xyz with a public team announcement. Every prior major airdrop has had phishing sites live within hours — never connect a wallet to any ''Monad claim'' URL that surfaces before the official one.',
      'potential',
      (SELECT id FROM chains WHERE slug = 'monad' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'testnet' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 244000000,
      200, 5000, 92,
      'https://monad.xyz', 'https://x.com/monad_xyz', 'https://discord.gg/monad',
      'y3A6LMDK',
      '2026-02-19', NULL, '2026-08-31'
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('y3A6LMDK', 'https://monad.xyz', (SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1), 0, 'Has Monad confirmed an airdrop?', 'No formal confirmation. The team has acknowledged that testnet activity ''will be considered'' for genesis distribution but hasn''t committed to a specific allocation. That said, every team in this $200M+ funding bracket (Berachain, Eclipse, MegaETH) has distributed 5–15% of supply to early users. The risk-adjusted bet is that there IS an airdrop; the open question is the formula and snapshot window.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1), 1, 'How do I avoid sybil filtering?', 'Three rules: (1) one wallet per identity, max 3–5 if you must run multiples — each with materially different behavioral profiles. (2) Fund wallets from different sources at different times, never from the same CEX withdrawal within the same hour. (3) Look like a real user — wash-trade between your own wallets and you''re guaranteed to be filtered. The team has stated they''re running clustering analysis on the testnet, so behavioral diversity matters from day one.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1), 2, 'When is the snapshot?', 'Unannounced. Mainnet is provisionally targeted for late 2026 / early 2027, and the team typically announces snapshots 2–4 weeks ahead of mainnet. Continued activity is your best position — anyone who stops farming after a ''rumored'' snapshot date often gets filtered when the real one is set.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1), 3, 'Is test-MON going to be the mainnet token?', 'No. Test-MON is testnet-only with no value or convertibility. Mainnet MON will be a new contract, and the genesis distribution will airdrop real MON tokens to qualifying wallets — not based on holding test-MON. Test-MON is purely a gas token for testing.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1), 4, 'Can US users participate?', 'Testnet participation has no geographic restriction. Mainnet airdrop eligibility for US wallets is unknown; some 2024–25 launches (LayerZero, Wormhole) allowed US claims, while others (EigenLayer) did not. Plan for the possibility you may need a non-US claim path. Verify on-chain transactions remain permissible from your jurisdiction regardless.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1), 5, 'How much capital should I commit?', 'Gas budget: $10–50 across the campaign. LP/lending capital: $50–200 maintained for several weeks. Total cost to qualify at a respectable bar: $100–300 tied up + gas. Anything more than $500 is overcommitting given the airdrop isn''t confirmed.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1), 6, 'Is KYC required?', 'No KYC at the protocol/claim level. CEX listings post-TGE may impose KYC at the exchange level if you want to sell on-CEX, but the on-chain claim itself is open.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'megaeth-testnet', 'MegaETH', 'MEGA', NULL, 'First ''real-time'' EVM rollup targeting sub-10ms block times. Vitalik-backed. Team has explicitly confirmed testnet activity will count toward token distribution — one of the few launches this cycle to do so.',
      'MegaETH is positioning itself as the first ''real-time'' EVM rollup, with sub-10ms preconfirmations and 100,000+ TPS targets. The architecture splits sequencer (single high-spec node) from proving (decentralized), trading some decentralization at the sequencer layer for radical latency improvements. The team — founded by Lei Yang, Yilong Li, and Shuyao Kong — has been building since 2023 under the EigenLayer-adjacent thesis that hardware-accelerated single-sequencer rollups can match the user experience of centralized exchanges.

The project raised **$30M in February 2024** at a $200M+ valuation, with backing from Dragonfly, Robot Ventures, Figment Capital, and an angel round that included **Vitalik Buterin personally** — one of his rare direct check-writings post-Ethereum genesis. Mert Mumtaz (Helius CEO), Sreeram Kannan (EigenLayer), and Cobie were also early backers.

Public testnet went live in **March 2026** after a year of private testnet. Within 8 weeks, more than 2.1M unique addresses had transacted on the testnet. The native ecosystem at launch: GTE (perps), Cap (money market), Ducks (NFT marketplace), Plume (RWA bridge).

The key reason MegaETH is one of the cleanest farming opportunities this cycle: the team has **explicitly confirmed publicly** that public testnet activity will be ''a meaningful input'' to the eventual token distribution. Most teams hedge this question; MegaETH said the quiet part out loud. Mainnet is targeted for Q4 2026 / Q1 2027, with the token distribution expected at or shortly after mainnet.

What works against farming MegaETH: the funding bracket is smaller than Monad ($30M vs $244M), implying a smaller total airdrop pool, but with a smaller eligible-farmer set the per-wallet allocation may compare favorably.', 'MegaETH has not published exact scoring weights but has confirmed several dimensions matter:

**Confirmed-meaningful inputs (from team statements):**
- Diversity of dapps interacted with — touching more native dapps scores higher
- Total testnet transaction count, weighted by recency
- Sustained balance held on MegaETH testnet (not bridged-in-and-out)
- Active trading on GTE (the team''s flagship perp DEX)

**Highly likely additional inputs (based on peer launches):**
- Time-weighted activity — sustained over 60+ days scores higher than burst
- Bridge volume from Sepolia (canonical bridge only)
- Lending or LP positions held across multiple weeks
- Participation in any governance experiments

**Likely filters:**
- Wallet count cap per identity cluster (probably 5)
- Activity-on-funding-day-only farms get cut
- Trading exclusively between own wallets (wash filter)

**Realistic targets:**
- **Minimum bar:** 30+ days of activity, 3+ native dapps used, 50+ transactions total
- **Recommended bar:** 60+ days, GTE perp trading volume of $1K+ (testnet ETH), Cap money-market position, 1+ Ducks NFT mint
- **Recommended wallet count:** 1–3 per identity
- **Gas budget:** $10–30 (testnet ETH is free from faucet, so cost is just Sepolia bridging gas)

Unlike Monad, MegaETH''s smaller eligible population and team-confirmed reward structure makes the EV/risk ratio attractive even at the minimum bar.', '1. **Fresh wallet.** Don''t reuse a wallet that''s touched known farms.
2. **Get test-ETH from the official faucet.** [testnet.megaeth.com/faucet](https://testnet.megaeth.com/faucet). Rate-limited per wallet per day.
3. **Bridge from Sepolia.** Use the canonical bridge linked from megaeth.com. Bridge 2–4 times across different days for natural-looking activity.
4. **Trade on GTE perps.** This is MegaETH''s flagship dapp. 5+ trades per week, varied size and direction. Don''t always go long — show realistic trading behavior. Cumulative testnet volume of $1K+ is a good target.
5. **Open a Cap position.** Lend or borrow on Cap money market. Even small testnet-USDC positions count. Maintain across the campaign.
6. **Mint a Ducks NFT.** Testnet mint, cheap. Adds a non-DeFi data point to your profile.
7. **Use Plume or other ecosystem dapps.** Variety is a scoring axis — sticking to just GTE makes you look like a trader-only.
8. **Maintain a positive testnet balance.** Don''t drain everything out at any point. Keep some test-ETH or test-USDC in the wallet at all times.
9. **Watch megaeth.com and the @megaeth_labs Twitter for the claim announcement.** Phishing risk is very high once mainnet ships — only the official channels are safe.',
      'potential',
      (SELECT id FROM chains WHERE slug = 'ethereum' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'testnet' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 30000000,
      300, 8000, 88,
      'https://megaeth.com', 'https://x.com/megaeth_labs', NULL,
      'sGUN0mtz',
      '2026-03-06', NULL, '2026-09-30'
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('sGUN0mtz', 'https://megaeth.com', (SELECT id FROM airdrops WHERE slug = 'megaeth-testnet' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'megaeth-testnet' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'megaeth-testnet' LIMIT 1), 0, 'Is the testnet open to anyone?', 'Yes — testnet.megaeth.com is open without an invite as of Q1 2026. Earlier private testnet phases required allowlisting; that gate has been removed for the public phase.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'megaeth-testnet' LIMIT 1), 1, 'What is the expected mainnet date?', 'Team has not committed publicly. Most signals (audit timelines, recent ecosystem partnerships) point to Q4 2026 / Q1 2027. The team has said multiple times they''d rather ship right than ship fast, so a slip into mid-2027 is possible.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'megaeth-testnet' LIMIT 1), 2, 'How is testnet usage actually measured?', 'The team confirmed three dimensions matter publicly: dapp diversity, transaction count weighted by recency, and sustained balance held. Exact weights are not published. Expect quality signals (sustained activity, native dapp use) to dominate quantity signals (raw transaction count) — this matches what every recent major launch has used.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'megaeth-testnet' LIMIT 1), 3, 'Why does Vitalik''s backing matter?', 'Two reasons: technical credibility (Vitalik rarely angel-checks unless he believes in the architecture) and signaling for the broader Ethereum community. It doesn''t guarantee an airdrop will happen, but it raises the social weight if/when one is announced — meaning the token will likely list immediately on top venues at launch.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'megaeth-testnet' LIMIT 1), 4, 'Can I farm MegaETH with the same wallet I''m farming Monad with?', 'Technically yes, but it''s not the optimal strategy. Each project runs its own clustering analysis, but using the same wallet across both means your activity profile is split — the wallet''s MegaETH-specific score is lower than if you had a dedicated wallet. If you have capital for it, separate wallets per chain is the higher-EV play.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'megaeth-testnet' LIMIT 1), 5, 'Is there KYC?', 'No KYC required at the protocol or claim level. CEX-side KYC may apply if you sell post-claim on Coinbase/Binance/etc., but the airdrop claim itself is on-chain only.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'megaeth-testnet' LIMIT 1), 6, 'What''s a reasonable monthly time commitment?', '30–60 minutes per week to maintain a high-quality farming profile. The bulk of effort is in the first week (setup, bridging, initial positions); subsequent weeks are just maintenance — a few trades and a position check.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'berachain-bgt-boost', 'Berachain BGT Boost', 'BGT', NULL, 'Live points + emissions program on Berachain''s Proof-of-Liquidity chain. Pays out weekly in USDC + ecosystem tokens. Confirmed and ongoing — no waiting for an unconfirmed airdrop.',
      'Berachain''s Proof-of-Liquidity (PoL) consensus is the only L1 in production that requires validators to direct emissions toward user-chosen reward vaults. The result is a tradable emissions market where liquidity providers earn **BGT** (governance) by LPing in whitelisted pools, then ''boost'' specific validators with their BGT to direct subsequent emissions back to themselves and the broader pool.

**This is unique among 2026 ''airdrops'': it''s already live and paying out, not a speculative future event.** Each weekly epoch distributes USDC, BERA, and ecosystem tokens (HONEY, iBGT, NECT) to boost participants. Total weekly emissions across the validator set: $250K–$500K depending on TVL and validator self-incentives. Per-wallet weekly earnings at $1K LP: typically $5–25 USDC equivalent, sometimes much more during incentive boosts.

Berachain raised **$142M** across two rounds (Series A: $42M led by Polychain, Series B: $100M led by Brevan Howard Digital and Framework). Mainnet went live February 6, 2026 with an initial airdrop distributed to NFT-holder cohorts and testnet farmers (already concluded — not part of this program).

BGT Boost is the SECOND wave of distribution: continuous emissions for ongoing participation, not a one-shot airdrop. Several Berachain-native protocols (Infrared, BeraBorrow, Honeypot, Kodiak, dolomite) stack additional incentives on top, layering yield on top of base BGT emissions. Yield-stacked APR on stable pairs has ranged 15–80% in the first three months of mainnet.

The core mechanic: BGT is **soulbound** (non-transferable). You can either burn it 1:1 for BERA (giving up future boost income) or boost validators (giving up the BERA conversion). Boosting is the higher-EV move while emissions are this generous.', 'Unlike speculative airdrops, BGT Boost is an open, on-chain program with explicit rules. Eligibility is mechanical:

**Required:**
- Acquire BGT by providing liquidity in any whitelisted BPL pool (HONEY/BERA, HONEY/USDC, iBGT/BERA, etc.)
- Stake the LP token in the matching reward vault to begin BGT accrual
- Delegate (Boost) accumulated BGT to at least one active validator
- Hold the boost position across at least one full weekly epoch (Mon→Mon)

**For meaningful yield:**
- Minimum $50–100 in LP to clear gas costs on weekly claims
- Use a validator whose self-incentives match your goal (USDC vs BERA vs ecosystem token)
- Layer with Infrared (auto-compounds BGT into iBGT, removes the soulbound friction) OR BeraBorrow (uses LP as collateral for NECT borrow) for stacked yield

**Things that DON''T affect yield:**
- Wallet count — boost yield is per-BGT, not per-wallet, so splitting wallets doesn''t help
- KYC status — no KYC, this is on-chain
- Geographic location — anyone with an EVM wallet can participate

**Strategy notes:**
- Validators publish their emission directions transparently. Rotate to validators with the best incentive packages for your goals.
- BGT cannot be unboosted instantly — there''s a 7-day cooldown before you can redirect. Plan your validator pick accordingly.
- iBGT (Infrared''s liquid wrapper) trades freely and can be sold on BEX — useful for exit liquidity if you want to lock in the yield without holding BGT long-term.
- Stable LP pairs (HONEY/USDC) have lower IL risk; volatile pairs (HONEY/BERA) capture more emissions when BERA price moves.', '1. **Bridge to Berachain.** Use bridge.berachain.com (canonical) or Stargate to bring ETH/USDC/wBTC over from Ethereum or Arbitrum. Native gas is BERA — buy a small amount on BEX after bridging.
2. **Open hub.berachain.com.** Connect wallet. Go to ''Pools''.
3. **Provide liquidity in a BPL pool.** Recommended starter: HONEY/USDC (stable, low IL). Add liquidity, receive LP tokens.
4. **Stake LP in the reward vault.** From the ''Vaults'' tab, find the matching vault for your LP token. Stake the LP tokens to begin earning BGT.
5. **Wait for BGT accrual.** BGT accrues per block proportional to your LP share + vault emission rate. Check your balance under ''My BGT''.
6. **Boost a validator.** Under ''Validators'', pick one whose incentive directions match what you want to earn (USDC, ecosystem tokens, etc.). Delegate your BGT to start receiving their incentives.
7. **Claim weekly.** Every Monday, claim accrued rewards from the ''Rewards'' tab. Reinvest or rotate to higher-APR validators as incentives shift.
8. **Optional: stack with Infrared.** Instead of boosting directly, deposit BGT into Infrared (infrared.finance). They auto-compound BGT into iBGT, which is liquid and can be sold or used as collateral. Lower hassle, slightly lower direct yield.',
      'confirmed',
      (SELECT id FROM chains WHERE slug = 'berachain' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'points' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 142000000,
      100, 3500, 84,
      'https://berachain.com', 'https://x.com/berachain', 'https://discord.gg/berachain',
      'SuMmSuC9',
      '2026-02-06', NULL, '2026-07-15'
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('SuMmSuC9', 'https://berachain.com', (SELECT id FROM airdrops WHERE slug = 'berachain-bgt-boost' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'berachain-bgt-boost' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'berachain-bgt-boost' LIMIT 1), 0, 'Is BGT transferable?', 'No — BGT is soulbound to the wallet that earned it. It can only be (1) redeemed 1:1 for BERA, (2) used to boost validators, or (3) wrapped via Infrared into liquid iBGT. The soulbound design is intentional: it prevents BGT speculators from front-running emissions.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'berachain-bgt-boost' LIMIT 1), 1, 'What''s the minimum to participate?', 'No hard minimum, but gas economics matter. Below $50 LP, weekly claim gas can eat your rewards. $100–500 LP is the comfortable starter range. Above $1K, the yield becomes meaningful and gas is a rounding error.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'berachain-bgt-boost' LIMIT 1), 2, 'Are rewards taxable?', 'In most jurisdictions yes — boost emissions are treated as ordinary income at the moment of accrual or claim (jurisdiction-dependent). The soulbound nature of BGT itself complicates basis tracking. Consult a tax professional; this is not advice.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'berachain-bgt-boost' LIMIT 1), 3, 'What''s the difference between BGT, BERA, and iBGT?', '**BERA** is the chain''s native gas token, transferable, sellable on CEXes. **BGT** is governance/emissions accrual, soulbound, only convertible to BERA 1:1 (burning future emissions) or usable for boosting. **iBGT** is Infrared''s liquid wrapper — you deposit BGT, Infrared boosts validators for you and gives you tradable iBGT in return. iBGT trades on BEX.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'berachain-bgt-boost' LIMIT 1), 4, 'Can I get IL''d?', 'Yes, especially on volatile pairs (HONEY/BERA). The PoL emissions can outpace IL during high-incentive periods, but a sustained BERA dump while you''re LP''d will hurt. Stable pairs (HONEY/USDC) have minimal IL and steady but lower emissions — better starting point.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'berachain-bgt-boost' LIMIT 1), 5, 'Is there a follow-up token airdrop on top of BGT Boost?', 'The initial Berachain airdrop already distributed (Feb 2026, to NFT holders + testnet farmers). BGT Boost is the continuous-emissions program post-mainnet. There''s been chatter about a future ecosystem-level airdrop targeting boost participants, but nothing confirmed.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'berachain-bgt-boost' LIMIT 1), 6, 'How do I exit?', 'Unstake LP tokens from the vault, withdraw liquidity from the pool, swap back to USDC/ETH, bridge out. Note: BGT itself can''t be sold — you can only burn it for BERA or leave it to keep boosting. Plan exit timing around BERA price action.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'sonic-airdrop-s2', 'Sonic Labs Points Season 2', 'S', NULL, 'Sonic''s S2 points program rewards activity on its high-speed EVM chain. Snapshot mid-September.',
      'Following S1''s $250M+ distribution, Sonic Labs has opened Season 2 of its points program. Points are earned for bridging assets, providing liquidity in whitelisted Sonic Gateway pools, and using Sonic-native dapps (SwapX, Beethoven X, Silo Finance V2). The S2 conversion ratio has been pre-announced at 200 points = 1 S token, with a hard cap on per-wallet allocations to combat sybils. Activity from S1 is not carried over — wallets must accrue fresh S2 points.', '- Bridge to Sonic via the official Gateway
- Accumulate points by holding stablecoins (1 pt / $ / day) or whitelisted LPs (2.5 pts / $ / day)
- Use SwapX or Beethoven X for at least 3 swaps per week
- Minimum 50,000 points required to qualify', '1. Bridge ETH or USDC to Sonic via https://gateway.soniclabs.com.
2. Park balance in a points-eligible vault — staked S, Silo USDC vault, etc.
3. Add LP on SwapX for the highest per-dollar rate.
4. Track your points via the official dashboard.
5. Snapshot is September 15, 2026 — keep position live until then.
6. Tokens will be claimable via the same dashboard 1-2 weeks after snapshot.',
      'live',
      (SELECT id FROM chains WHERE slug = 'ethereum' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'points' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 0,
      150, 4000, 76,
      'https://sonic.fan', 'https://x.com/0xSonicLabs', NULL,
      'esrMVhyB',
      '2026-04-01', '2026-09-15', '2026-09-30'
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('esrMVhyB', 'https://sonic.fan', (SELECT id FROM airdrops WHERE slug = 'sonic-airdrop-s2' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'sonic-airdrop-s2' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'sonic-airdrop-s2' LIMIT 1), 0, 'Did S1 actually distribute?', 'Yes — Sonic''s S1 distributed in early 2026 and trades on most major exchanges. S2 conditions are similar.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'sonic-airdrop-s2' LIMIT 1), 1, 'Is there a per-wallet cap?', 'Yes — the team has indicated a soft cap around 1M points per wallet. Beyond that the marginal allocation tapers significantly.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'symbiotic-points', 'Symbiotic', NULL, NULL, 'Paradigm-backed restaking protocol — EigenLayer''s main competitor. Cap-gated deposit program where every cap fills within hours. Points → token at TGE, expected H1 2027.',
      'Symbiotic is a permissionless restaking protocol competing directly with EigenLayer. The key technical differentiator: Symbiotic accepts **any asset** as collateral (not just ETH derivatives), enabling LRTs, stablecoins, project-specific tokens, and LP tokens to back AVS-style services. The architecture decouples staking from slashing logic and lets AVS operators define their own collateral whitelists — meaning a single AVS can be backed by, say, wstETH + cbETH + sUSDe + project-token simultaneously.

The team — led by Misha Putiatin (ex-StakeWise founder) and the Lido Finance early contributor circle — raised **$5.8M seed** in Q1 2024 led by Paradigm. The current round (in progress, not publicly priced) is reported to value the protocol at $1B+ pre-TGE. Strategic partnerships include Mellow (LRT wrapping layer), Pendle (yield trading), Ether.fi (LRT issuer), Lido (stETH integration), and Karak (cross-restaking).

The points program launched in **January 2026** with hard deposit caps. Each cap opening has been **filled within 2–6 hours** of going live, with deposit waitlists running into the thousands. This is the clearest signal of pre-TGE demand for any restaking protocol since EigenLayer''s 2024 deposit cap race. Total TVL across Symbiotic vaults crossed **$2.4B** by April 2026.

The expected outcome: points convert to tokens at TGE (targeted H1 2027). Looking at peer launches — EigenLayer''s EIGEN distributed ~$0.05–0.15 per point, Ether.fi''s ETHFI distributed ~$0.20–0.50 per point at peak — Symbiotic points are widely expected to land in a similar range. With a Paradigm-led raise at $1B+ valuation, the implied airdrop pool is sizable.

Most important fact about the points program: **multipliers stack significantly**. Direct Symbiotic deposit gives base points. Routing through Mellow or Ether.fi LRT layers adds 1.5–3x multipliers on top of the underlying Symbiotic point accrual, plus those wrappers'' own points. The optimal strategy is rarely ''deposit directly'' — it''s ''route through a multiplier LRT''.', 'Eligibility is mechanical: have points, get tokens. The strategic question is how to maximize point accrual per dollar deposited.

**Acceptable collateral (vault-dependent):**
- wstETH (Lido staked ETH wrapper) — most common
- cbETH (Coinbase staked ETH)
- swETH (Swell staked ETH)
- rETH (Rocket Pool staked ETH)
- sUSDe (Ethena staked synthetic dollar) — high APY, more volatile
- Token-specific vaults (when AVS operators whitelist their own token)

**Required:**
- Deposit a supported asset into an open Symbiotic vault (subject to caps — set a calendar reminder for cap opens)
- Maintain the position across at least one weekly epoch (Mon→Mon UTC)
- Don''t withdraw early — withdrawals forfeit accumulated multipliers from the current epoch

**Multiplier-stacking strategies (highest EV first):**
1. **Mellow vault routing.** Deposit via Mellow (mellow.finance) into their Symbiotic-backed strategies. You earn Mellow points + Symbiotic points + base staking yield, with a 1.5–3x multiplier on Symbiotic points depending on the vault.
2. **Ether.fi LRT routing.** Deposit ETH into Ether.fi''s eETH or weETH, then deposit into a Symbiotic vault that whitelists weETH. You earn ETHFI points + Symbiotic points + base yield.
3. **Direct Symbiotic deposit.** Simplest, no multiplier, but no third-party smart-contract risk on top.
4. **Pendle YT (advanced).** Buy Pendle YT (yield token) on weETH or wstETH, which captures points exposure at a fraction of the principal cost. Higher leverage on points, but YT decays to zero at maturity — only use if you understand the math.

**Don''t:**
- Withdraw mid-epoch to chase a different vault — you lose multipliers
- Park funds in a vault with a closed deposit cap thinking caps re-open (they typically don''t)
- Use cross-chain bridging that''s not officially supported — funds can get stuck', '1. **Acquire supported collateral.** Easiest path: have ETH, stake it via Lido (lido.fi) → receive stETH → wrap to wstETH (wsteth.eth). Or buy stETH directly on Uniswap/Curve.
2. **Check Symbiotic vault caps.** Go to [app.symbiotic.fi](https://app.symbiotic.fi). The ''Vaults'' page shows current cap utilization. Most popular vaults are perpetually 100% — watch for cap expansions, which are announced on @symbioticfi.
3. **Pick your routing strategy.** Direct = simple, Mellow/Ether.fi = multiplier stacks. For most users with $1K–10K, Mellow vault routing is the best risk/reward.
4. **Deposit when a cap opens.** Caps fill in 2–6 hours. Don''t dawdle — set a notification on @symbioticfi.
5. **Track points.** The dashboard at app.symbiotic.fi shows your accruing points in near-real-time. Mellow''s dashboard shows the multiplied total.
6. **Hold position across weekly epochs.** Epochs run Mon→Mon UTC. Don''t withdraw until the epoch closes if you want full credit for the week.
7. **Watch for the TGE announcement.** Expected H1 2027 based on peer-launch cadences. The claim portal will be on app.symbiotic.fi — only the official URL.
8. **Do NOT** interact with any ''Symbiotic claim'' site that surfaces before the team''s announcement.',
      'live',
      (SELECT id FROM chains WHERE slug = 'ethereum' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'points' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 5800000,
      100, 6000, 81,
      'https://symbiotic.fi', 'https://x.com/symbioticfi', NULL,
      'IrupFfTk',
      '2026-01-15', NULL, NULL
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('IrupFfTk', 'https://symbiotic.fi', (SELECT id FROM airdrops WHERE slug = 'symbiotic-points' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'symbiotic-points' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'symbiotic-points' LIMIT 1), 0, 'What''s the conversion rate (points → tokens)?', 'Not announced. Comparable protocols set precedent: EigenLayer''s EIGEN distributed ~$0.05–0.15 per point at launch; Ether.fi''s ETHFI distributed ~$0.20–0.50 per point. Symbiotic''s peer-implied rate is probably in the $0.05–0.30 range, depending on TGE valuation and total points outstanding. Volume of deposits suggests the team will set the rate to make whales meaningful but not whale-only.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'symbiotic-points' LIMIT 1), 1, 'Can I withdraw early?', 'Yes — Symbiotic has no lock-up on the deposit itself (slashing windows aside). BUT withdrawing mid-epoch forfeits that epoch''s accumulated multipliers. If you need to exit, time it after Monday UTC epoch close to keep that week''s credit.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'symbiotic-points' LIMIT 1), 2, 'Is there slashing risk?', 'Yes, in principle. Symbiotic is a restaking protocol — the whole point is that AVSes can slash misbehaving operators. But in practice (as of mid-2026), no AVS on Symbiotic has executed a slashing event. Risk-adjusted, slashing is currently a theoretical risk for end-depositors rather than an operational one. This will change as more AVSes go live.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'symbiotic-points' LIMIT 1), 3, 'Mellow vs direct deposit vs Pendle YT — which is best?', 'For most users with $1K–10K: **Mellow** is the best risk/reward. 1.5–3x multiplier on Symbiotic points + Mellow''s own points stack + base yield. For sophisticated users with the math down: **Pendle YT** gives the highest points-per-dollar by isolating yield exposure. For paranoid users wanting minimal smart-contract surface area: **direct deposit**. The Pendle path has the highest upside but also the highest downside (YT decays to zero at maturity — only use if you understand the term structure).');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'symbiotic-points' LIMIT 1), 4, 'How do deposit caps work?', 'Each vault has a TVL cap set by Symbiotic. When a cap is reached, deposits are blocked. The team periodically raises caps as new AVSes come online or new collateral types are whitelisted. Cap expansions are announced on Twitter @symbioticfi — fill within hours. Closed caps almost never re-open after first fill, so missing a cap means missing that vault entirely.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'symbiotic-points' LIMIT 1), 5, 'Is KYC required?', 'No KYC at the protocol level. The deposit is fully on-chain. KYC may apply for US users at the eventual TGE if a centralized exchange handles distribution, but the on-chain claim itself is permissionless.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'symbiotic-points' LIMIT 1), 6, 'When is TGE expected?', 'The team has not committed publicly. Based on peer cadences (EigenLayer: 18 months from points program launch to TGE; Ether.fi: 14 months), expect Symbiotic TGE in **H1 2027**. The cap-fill velocity and Paradigm-led round timing both support that estimate.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'polymarket-trader-drop', 'Polymarket Trader Rewards', NULL, NULL, 'Largest prediction market on the planet, recently relisted in the US via QCX acquisition. $200M raise in early 2026 + token-shaped product moves make a 2026 TGE the highest-probability bet in this category.',
      'Polymarket is the largest crypto-native prediction market and the most-watched candidate for a 2026 token launch. The platform processes the bulk of global prediction-market volume across politics, sports, crypto, and macro events. Founded by Shayne Coplan in 2020, the company has progressed from regulatory grey-zone status to fully US-legal in under 18 months.

**Funding and corporate moves:**
- $74M Series B (Aug 2023, led by Founders Fund / Peter Thiel)
- **$200M+ round (Q1 2026)** with participation from a16z, Founders Fund, and Vitalik Buterin personally
- **QCX acquisition (late 2025)** — the CFTC-regulated derivatives exchange that gave Polymarket a legal path back to US users
- Public endorsements from Vitalik Buterin (technical legitimacy) and the Anthropic founder cohort (mainstream credibility)

**Why a token is now likely:**
1. **Funding bracket.** $270M+ total raised at a $1B+ valuation puts Polymarket in the funding range where every comparable crypto-native platform has launched a token within 12–18 months (Hyperliquid, dYdX, Jupiter, Aevo).
2. **Regulatory clarity.** Pre-2025, a Polymarket token was a US-legal landmine. Post-QCX, the regulatory cover exists.
3. **Competitive pressure.** Kalshi (Polymarket''s main competitor) does not have a token, but multiple smaller competitors (Edgehog, BetU, Augur successors) are token-launching. Polymarket has obvious strategic value in capturing aligned-user attention via a token before competitors do.
4. **Product signals.** The team has added a ''rewards'' tab in the UI and rolled out point-style attributions on certain markets — both common pre-token-launch fixtures.

**What the team has NOT done:**
- Formally announce a token
- Launch a points program (the platform has rewards but they''re per-market, not platform-wide)
- Publish tokenomics

**The risk:** Polymarket''s US legal status post-QCX makes a token launch more complex, not less. The CFTC-regulated structure puts limits on what tokenomics can include (governance over market resolution = potentially a security). The team may choose to keep equity-only ownership.

**The base case:** if Polymarket launches a token in 2026–2027, the highest-probability recipients are active traders, with allocation roughly proportional to trading volume and market diversity. Estimated per-wallet airdrop value at peer-launch precedent: $500–10,000 for moderate-to-high-volume traders, with the top ~1% potentially much higher.', 'Polymarket has not published criteria, so the eligibility analysis is based on what comparable launches (Hyperliquid, dYdX, Aevo, Jupiter) used. All of them rewarded active traders weighted by volume + diversity.

**Likely-meaningful inputs:**
- **Total notional volume traded.** Probably the dominant factor. Cumulative $1K+ across the lifetime of your account is likely the floor; $10K+ puts you in the meaningful tier.
- **Market diversity.** Trading across categories (politics, sports, crypto, macro) scores higher than concentrating in one. Hyperliquid weighted this heavily.
- **Holding losing positions to resolution.** Real users sometimes lose; pure-arb farmers don''t. Activity that includes losses scores higher than 100%-win patterns.
- **Account age and consistency.** Continuous-use accounts score higher than ''fresh wallet right before snapshot''.
- **Withdraw frequency.** Real users withdraw winnings. Accounts that never withdraw look like volume-farms.

**Likely-irrelevant:**
- Stake on individual market outcomes — the snapshot is about activity, not predictions
- Number of markets created — Polymarket doesn''t let retail create markets

**Filtered out:**
- Wash-trading between own accounts (trivially detected on Polymarket since each market has limited liquidity)
- Bot-style market-making patterns (unless you''re a designated market-maker with disclosed identity)
- Coordinated cluster behavior across many accounts

**Realistic targets:**
- **Minimum bar:** $1K cumulative volume across 10+ distinct markets, 3+ months activity history
- **Meaningful bar:** $10K cumulative volume across 30+ markets, 6+ months activity
- **Whale tier:** $100K+ cumulative volume — likely the top airdrop bracket if it happens

**Geographic note:**
- US users CAN now trade on Polymarket post-QCX. Whether US users CAN CLAIM an eventual token is a separate question Polymarket has not commented on. If you''re a US user, your trading activity might count even if the eventual token is restricted to non-US wallets at claim.', '1. **Sign up at [polymarket.com](https://polymarket.com).** KYC is required (light — name + email + jurisdiction). US users go through the QCX-regulated flow.
2. **Deposit USDC to Polygon.** Polymarket runs on Polygon. Bridge USDC from Ethereum or your CEX. Min deposit usually $10.
3. **Trade across diverse markets.** Politics + sports + crypto is the recommended starter mix. Aim for 10+ distinct markets in your first month.
4. **Hold positions to resolution.** Don''t just open and immediately close. Real users sit on positions, and resolved trades (win or lose) score better than open-close churn.
5. **Maintain a 3+ month activity history.** Trade consistently — once or twice per week is sufficient. Don''t go dark for long stretches.
6. **Withdraw winnings occasionally.** Pull profits to a wallet you control once in a while. Accounts that never withdraw look like volume-farms.
7. **Watch official channels:** [@Polymarket](https://x.com/Polymarket) on X, the polymarket.com blog. The phishing site density around Polymarket is one of the highest in crypto — never click ''Polymarket airdrop'' URLs from social media. If a token announcement happens, it will be on polymarket.com first.
8. **Pre-snapshot strategy:** when a token announcement happens, don''t dramatically change your trading pattern. Continued normal activity scores better than burst-trading right before snapshot.',
      'potential',
      (SELECT id FROM chains WHERE slug = 'ethereum' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'task' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 70000000,
      500, 10000, 95,
      'https://polymarket.com', 'https://x.com/Polymarket', NULL,
      'w284ty4w',
      '2026-05-01', NULL, NULL
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('w284ty4w', 'https://polymarket.com', (SELECT id FROM airdrops WHERE slug = 'polymarket-trader-drop' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'polymarket-trader-drop' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'polymarket-trader-drop' LIMIT 1), 0, 'Is a Polymarket token confirmed?', 'No. The team has NOT formally announced a token, points program, or distribution event. But the structural setup — $270M+ total raised, US re-entry via QCX, competitor pressure, product moves that look pre-token-launch — mirrors every prior crypto-native platform that issued a token within 12–18 months. The base-case probability of a 2026–2027 token launch is in the 60–80% range.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'polymarket-trader-drop' LIMIT 1), 1, 'Will US users qualify?', 'Unknown. Two layers here: (1) US users CAN now trade on Polymarket post-QCX. (2) Whether US wallets can CLAIM an eventual token is separate and unannounced. Some prior US-blocked tokens (LayerZero, Eigen) allowed US claims; others (Aevo) did not. Polymarket''s CFTC-regulated structure adds complexity — a governance token over real-money markets may legally require non-US distribution. Plan optimistically, accept the risk that US claims may be restricted.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'polymarket-trader-drop' LIMIT 1), 2, 'How much volume should I target?', '**Floor:** $1K cumulative volume + 10+ markets + 3+ months activity. **Comfortable:** $10K + 30+ markets + 6+ months. **Whale tier:** $100K+ — likely the largest per-wallet bracket if a token launches. Don''t over-leverage to hit volume targets — you can lose principal trading prediction markets, and there''s no guarantee the airdrop materializes.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'polymarket-trader-drop' LIMIT 1), 3, 'Should I trade markets I''d lose money on just to farm?', 'Generally no — losing $1K to farm a maybe-$2K airdrop is bad EV. But the airdrop scoring likely rewards ''real user'' patterns over ''perfect-arbitrageur'' patterns. Don''t go out of your way to lose, but don''t avoid markets where you have a genuine view just because they might lose either. Mix it up.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'polymarket-trader-drop' LIMIT 1), 4, 'What''s the phishing landscape?', 'Polymarket is one of the most-impersonated platforms in crypto. ''polymarket-claim.com'', ''polymarketrewards.io'', etc. all exist as drainer sites. Rules: (1) Only polymarket.com is real. (2) Polymarket will NEVER message you on Discord/Telegram about an airdrop. (3) The team almost certainly will NOT require a wallet signature to ''verify'' anything — same rule as everywhere on this site.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'polymarket-trader-drop' LIMIT 1), 5, 'Is KYC required at the token claim?', 'Unknown. KYC IS required for trading on Polymarket already (US users via QCX especially). The claim itself may or may not require additional KYC; this varies by jurisdiction and how the team structures the distribution. If you''ve already passed KYC to trade, you''re past the hardest gate.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'polymarket-trader-drop' LIMIT 1), 6, 'What''s the time horizon?', 'Best guess: TGE in H2 2026 or H1 2027. The fundraise closed Q1 2026; comparable launches typically run 9–15 months from large round to TGE. Anyone telling you a more specific date is guessing.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'walrus-storage-testnet', 'Walrus', 'WAL', NULL, 'Mysten Labs'' decentralized blob storage on Sui — testnet stakers and storage users are tracked for the WAL drop.',
      'Walrus is a decentralized storage protocol built on Sui by Mysten Labs (the team behind Sui itself). It uses erasure coding (Red Stuff) to store large blobs at significantly lower cost than competitors like Filecoin or Arweave. The team has confirmed a WAL token launch and an initial community distribution targeting testnet storage users, validators, and Sui ecosystem participants. Snapshot is June 30 2026.', '- Hold and stake SUI through a Walrus-eligible validator
- Upload at least 100MB of test blobs to the Walrus testnet
- Run a Walrus storage node (advanced — Linux required)', '1. Acquire SUI on a CEX or DEX and bridge to Sui mainnet.
2. Visit walrus.xyz and connect a Sui wallet.
3. Upload test data via the Walrus CLI or UI.
4. Wait for snapshot, then claim on the official portal after TGE.',
      'confirmed',
      (SELECT id FROM chains WHERE slug = 'sui' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'testnet' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 13000000,
      80, 1500, 72,
      'https://walrus.xyz', 'https://x.com/WalrusProtocol', NULL,
      'fAmI53aS',
      '2026-03-15', '2026-06-30', '2026-07-15'
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('fAmI53aS', 'https://walrus.xyz', (SELECT id FROM airdrops WHERE slug = 'walrus-storage-testnet' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'walrus-storage-testnet' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'walrus-storage-testnet' LIMIT 1), 0, 'Is the WAL drop confirmed?', 'Yes — Mysten Labs has formally announced WAL with an explicit community distribution component.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'humanity-protocol-genesis', 'Humanity Protocol', 'H', NULL, 'Palm-scan biometric proof-of-humanity. KYC-style verification required, but verified humans earn daily H credits.',
      'Humanity Protocol uses palm-vein recognition to issue sybil-resistant proof-of-personhood credentials, competing directly with Worldcoin. Verified users earn daily H token credits convertible at TGE. Because the verification is biometric, KYC-style data is collected — this is the major caveat for privacy-conscious users.', '- Verify with a Humanity Protocol Verifier (in-app palm scan)
- Open the app daily to claim H credits
- Refer additional verified humans for boosted credits', '1. Install the Humanity Protocol app from your phone''s app store.
2. Complete the palm-vein verification at a Verifier (in-person required in some regions).
3. Open the app every 24h to claim accruing H credits.
4. Claim portal will activate at TGE; tokens issued to the verified address.',
      'live',
      (SELECT id FROM chains WHERE slug = 'ethereum' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'task' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      1, 32000000,
      50, 1200, 68,
      'https://humanity.org', 'https://x.com/Humanityprot', NULL,
      'dvrAHooO',
      '2026-02-01', NULL, '2026-12-31'
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('dvrAHooO', 'https://humanity.org', (SELECT id FROM airdrops WHERE slug = 'humanity-protocol-genesis' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'humanity-protocol-genesis' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'humanity-protocol-genesis' LIMIT 1), 0, 'Is biometric data stored?', 'Humanity Protocol claims biometric data is processed locally and only a zero-knowledge commitment is stored on-chain. Critics dispute the strength of these guarantees.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'humanity-protocol-genesis' LIMIT 1), 1, 'Is this safe for me?', 'Only you can decide. Biometric data, once leaked, cannot be reset. We provide no recommendation either way.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'linea-surge-points', 'Linea Surge', NULL, NULL, 'ConsenSys''s zkEVM has no token yet. Linea Surge LXP-L points and ecosystem TVL programs are the most likely qualifier paths.',
      'Linea is ConsenSys''s zkEVM rollup. It has not yet announced a native token, but the team runs an active points program (LXP-L) tied to provable on-chain actions and a ''Surge'' program tied to TVL bridged into Linea-native DeFi (Lynex, Mendi, etc.). MetaMask-native integration positions Linea for a large eventual user base.', '- Bridge ETH to Linea via the canonical bridge
- Provide liquidity in Linea Surge-eligible pools
- Hold LXP and LXP-L points (earned through Galxe quests and on-chain activity)', '1. Bridge ETH at bridge.linea.build.
2. Complete monthly Galxe quests at linea.build/hub.
3. Provide LP in Lynex or Mendi.
4. Watch for the eventual token announcement.',
      'potential',
      (SELECT id FROM chains WHERE slug = 'linea' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'points' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 0,
      100, 3000, 70,
      'https://linea.build', 'https://x.com/LineaBuild', NULL,
      'P9f0drU3',
      '2026-01-10', NULL, NULL
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('P9f0drU3', 'https://linea.build', (SELECT id FROM airdrops WHERE slug = 'linea-surge-points' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'linea-surge-points' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'linea-surge-points' LIMIT 1), 0, 'Has Linea confirmed a token?', 'No. Joseph Lubin (ConsenSys) has hedged on the question publicly but the LXP/LXP-L point design strongly resembles a pre-TGE accumulation system.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'tapswap-season-3', 'TapSwap Season 3', 'TAPS', NULL, 'Telegram tap-to-earn mini-app, S3 cohort. Low effort, low EV — but qualifying takes 5 minutes a day.',
      'TapSwap is a Telegram-native tap-to-earn game on TON. S1 distributed real tokens; S2 was modest; S3 is now active. Expected value per wallet is small ($5-$50 typical) but the time investment is correspondingly low. Useful as a ''free shot'' in a diversified airdrop strategy.', '- Have a Telegram account in good standing (not freshly created)
- Mine taps daily and complete the daily checklist
- Connect a TON wallet (Tonkeeper or similar) for claim', '1. Open https://t.me/tapswap_bot inside Telegram.
2. Mine taps each day until energy depletes.
3. Complete the daily quests for boosters.
4. Connect a TON wallet before snapshot.
5. Claim is automatic to the connected wallet post-snapshot.',
      'live',
      (SELECT id FROM chains WHERE slug = 'ton' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'telegram' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 0,
      5, 200, 60,
      'https://tapswap.club', 'https://x.com/tapswap_mining', NULL,
      '_hETRvQx',
      '2026-04-10', '2026-07-20', '2026-07-31'
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('_hETRvQx', 'https://tapswap.club', (SELECT id FROM airdrops WHERE slug = 'tapswap-season-3' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'tapswap-season-3' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'tapswap-season-3' LIMIT 1), 0, 'Are tap-to-earn drops worth my time?', 'Marginally. Expect $5-$50 for 5 min/day over a few months. Skip if your time is worth more than that hourly.');

-- guides
INSERT INTO guides (slug, title, excerpt, body_md, published_at) VALUES ('avoid-connect-wallet-airdrop-scams', 'How to avoid the "connect wallet to verify" airdrop scam (2026 update)', 'Pasting a public address to check airdrop eligibility is safe. Signing a transaction to ''verify'' your wallet is how almost every airdrop draining attack of 2024-2026 started. Here''s exactly what to watch for.', '## Why this matters

The single biggest financial risk in the airdrop space is not picking the wrong project — it''s getting drained by a fake checker site. Throughout 2024, 2025, and into 2026, the dominant attack pattern has stayed identical: lure users to a fake "airdrop checker" or "claim portal" with a Google Ad or Twitter reply, ask them to "connect wallet to verify eligibility," then drain everything in the wallet via a hidden malicious signature.

The attack is so durable because the user-facing prompt looks identical to a legitimate dapp interaction. If you understand exactly what is happening under the hood, the warning signs become obvious.

## What "connect wallet" actually does

Connecting a wallet to a site does NOT, on its own, give the site any power to move your funds. Connection only shares your public address. The site needs you to *sign* something to do anything malicious.

The danger is in the very next prompt that almost always follows. The site will request one of these signature types:

- `permit` or `permit2` — gives the site permission to spend a specific token without a separate approval transaction. One signature, your stablecoins are gone.
- `setApprovalForAll` — gives blanket NFT spend rights. Your Bored Ape is gone in the next block.
- A swap or transfer transaction that has been crafted to drain a specific token.

Legitimate airdrop checkers DO NOT need any of these signatures. Pasting a public address is enough to query the blockchain.

## The cardinal rule

> If a site asks you to sign anything to *check* eligibility, close the tab.

The only signature that should appear during a real airdrop flow is the actual **claim transaction**, after the snapshot, on the project''s official URL. And even then, simulate it in a wallet that supports transaction simulation (Rabby, Frame, OneKey) before approving.

## How to verify a checker is safe

1. **URL check.** Type the official URL by hand. Never click a link from a reply, DM, or sponsored search result. Bookmark legit sites the first time you visit.
2. **No connection prompt.** A safe checker has a text input for an address. That''s it. No "Connect Wallet" button on the checker page.
3. **Read-only confirmation.** The checker explicitly states it does not request signatures. (Ours does — see the [/check page](/check).)
4. **No urgency.** Real airdrops do not have "claim in the next 5 minutes or lose forever" timers. Anything that pressures speed is a phish.

## Wallet hygiene if you farm airdrops

- Use a **fresh wallet** with no other funds for any interaction with a new dapp.
- After confirming a dapp is safe, you can graduate it to your "farming" wallet with small balances.
- **Never** sign anything from your main wallet that holds long-term assets.
- Use a **hardware wallet** for the main vault. The cost is $80; the upside is a drainer can''t pull funds without physical confirmation.
- Revoke approvals quarterly via [revoke.cash](https://revoke.cash).

## What to do if you''ve already signed something suspicious

1. Move every asset out of the affected wallet immediately to a fresh wallet — gas willing.
2. Revoke all approvals on revoke.cash (this may not save you if a `permit` was already used to transfer).
3. Report the phish on Twitter / Telegram so others avoid it.
4. Assume the wallet is permanently compromised. Never use it again, even after revoking.

## Bottom line

Paste, don''t sign. Every credible airdrop checker — including this one — works on public addresses alone. Treat any prompt for a signature during eligibility verification as definitive proof you''re on a phishing site, and close the tab.', '2026-05-10') ON DUPLICATE KEY UPDATE title=VALUES(title), excerpt=VALUES(excerpt), body_md=VALUES(body_md), published_at=VALUES(published_at);
INSERT INTO guides (slug, title, excerpt, body_md, published_at) VALUES ('how-to-qualify-for-l2-airdrops-2026', 'How to qualify for L2 airdrops in 2026 (without sybil flagging)', 'A practical playbook for farming L2 airdrops that survive the inevitable sybil filter. Diversity beats volume; consistency beats burst farming; and unique behavioral signatures beat bot-perfect activity.', '## What changed in 2026

The ZK-rollup wave of 2024-2025 (zkSync, Starknet, Linea, Scroll) trained teams how to filter sybils aggressively. Every major L2 airdrop since LayerZero has applied multi-axis sybil detection: address-graph clustering, behavioral fingerprinting, fund-source analysis, and timing distribution. Pre-2024 farming techniques (50-wallet stamping, identical-amount transactions, same-day funding) are now reliably filtered out.

The modern L2 airdrop is best understood as **a behavioral pattern recognition contest, not a volume contest**. You are trying to look like a real user who happens to use multiple wallets, not a farmer.

## The signals that matter

From every published sybil-detection methodology (Hop Protocol''s, LayerZero''s, Optimism''s), these are the axes graders use:

1. **Funding source diversity.** Wallets funded from the same CEX address within the same hour are clustered. Use different CEXes, different times, different amounts. Better: peer-to-peer funding from a fresh wallet you control, mixed with CEX withdrawals.
2. **Time distribution.** Real users don''t transact in 5-minute bursts on 30 wallets. Spread activity across days and weeks, with natural gaps.
3. **Dapp diversity.** Touching only the bridge marks you as a farmer. Real users swap, lend, mint NFTs, vote, and bridge.
4. **Transaction value variance.** All your txs being $10 ± $1 is a red flag. Real value distributions are skewed and noisy.
5. **Gas pattern.** Submitting only at minimum priority fee marks you. Sometimes overpay; sometimes wait.
6. **Holding behavior.** Bridge → swap → bridge back same day = farmer. Bridge → keep position for weeks = user.

## The minimum viable strategy

For any active L2 with a likely retroactive drop:

- **30+ days** between first activity and snapshot. Anything shorter is increasingly filtered.
- **3+ unique dapps** touched: bridge + DEX + lending or NFT.
- **5-15 transactions/month** across those dapps. Quality over quantity.
- **Maintain a non-trivial position** (e.g., $50+ LP, $100+ lent) across the snapshot.
- **Do something native to the chain** — a Linea-only protocol, a Base-only mint, a Scroll-only social app. Generic protocols deployed everywhere are deprioritized.

## Wallet count tradeoff

1 wallet that looks like a real user beats 20 wallets that look like farmers. If you must run multiples:

- Maximum 3-5 wallets across an L2.
- Each wallet funded from a different source.
- Each wallet''s behavioral profile materially different (one heavy DEX, one heavy lending, one heavy NFT).
- No common withdrawal address pre-snapshot.

More than 5 wallets per L2 is a losing strategy in 2026.

## Chains worth farming right now

At time of writing (May 2026):

- **Monad** — testnet active, no token, $244M raised, very likely retroactive.
- **MegaETH** — testnet active, team has confirmed activity will be counted.
- **Linea** — LXP/LXP-L points active, ConsenSys has not committed to a token but the system is designed like a pre-TGE accumulation.
- **Berachain** — mainnet live, BGT boost emissions are paying out weekly.
- **Sonic** — Season 2 points open through September 2026 snapshot.

See the [/check page](/check) to test whether any wallets you''ve already used would qualify for finalized snapshots.

## What kills your allocation

- **Funding from a sanctioned mixer.** Allocation goes to zero. Use clean funds.
- **Behavioral clustering with known farms.** If your wallet''s behavior matches a published sybil cluster, you''re cut.
- **Trading exclusively with yourself.** Wash trades across your own wallets are detected by every modern grader.
- **Activity ending exactly at snapshot.** A natural user keeps using the chain after the airdrop too. Many graders include a post-snapshot continuation check.

## Bottom line

Farming L2 airdrops profitably in 2026 means looking like a real user who has multiple wallets, not a farmer trying to look like a real user. The fewer wallets, the more diverse the behavior, the longer the timeline, the higher the expected value per wallet.', '2026-04-28') ON DUPLICATE KEY UPDATE title=VALUES(title), excerpt=VALUES(excerpt), body_md=VALUES(body_md), published_at=VALUES(published_at);
INSERT INTO guides (slug, title, excerpt, body_md, published_at) VALUES ('what-is-a-retroactive-airdrop', 'What is a retroactive airdrop? (And why they''re the highest-EV category)', 'A retroactive airdrop rewards on-chain activity that already happened before the token was announced. They consistently produce the largest per-wallet payouts — but only for users who happened to use the protocol naturally, which is the catch.', '## Definition

A retroactive airdrop distributes tokens to wallets that interacted with a protocol *before* the token was announced. The protocol team takes an on-chain snapshot of historical users, applies a scoring formula, and allocates tokens proportionally.

Key distinction from other airdrop types:

- **Retroactive** rewards past activity. You qualify by accident, by being an early user. Examples: Uniswap (UNI, 2020), 1inch, dYdX V2, ENS, Arbitrum (ARB), Optimism (OP), LayerZero (ZRO), Wormhole (W), Jupiter (JUP).
- **Points / live programs** reward present activity. You qualify by participating in a known points system. Examples: EigenLayer points, Ether.fi loyalty, Pendle YT.
- **Testnet** rewards activity on a chain''s testnet pre-mainnet. Examples: Aptos, Sui, ZK-Sync (partially), Monad (upcoming).
- **Task-based** rewards completing a defined quest, usually via Galxe or Zealy.

## Why retroactive drops have the highest historical EV

Three reasons:

1. **Smaller eligible population.** Pre-announcement users are by definition early adopters. The denominator on token-per-wallet is small.
2. **Strong product-market fit signal.** Protocols willing to distribute retroactively typically have real users and revenue — these aren''t vapor coins. The token retains value better.
3. **Lower farming risk.** You can''t farm what hasn''t been announced. The early users qualified through genuine usage, not deliberate gaming, which limits sybil dilution.

**The catch:** by definition, you can''t *target* a future retroactive drop, because they''re not announced. The best you can do is interact with high-quality protocols that *might* tokenize, betting that some of them will reward early activity.

## The retroactive-drop heuristic

Protocols that are most likely to do a retroactive drop tend to:

- Have raised $20M+ from top-tier VCs (Paradigm, a16z, Coinbase Ventures, Polychain).
- Have a tokenless competitor that already tokenized (creates pressure).
- Be deployed for 12+ months with measurable user growth and TVL.
- Have a public Discord with talk of "community ownership" but no token announcement.
- Be on an L2 or L1 that itself rewarded retroactively (Arbitrum, Optimism, Base ecosystem protocols).

DefiLlama''s [airdrops page](https://defillama.com/airdrops) tracks the universe of tokenless protocols — a useful candidate list. We pull from this source for our [home page](/) listings.

## How retroactive scoring usually works

The exact formula is always different, but common ingredients:

- **Time-weighted volume.** Activity that happened earlier in the protocol''s life weighs more.
- **Diversity bonus.** Using multiple features of the protocol scores higher than only using one.
- **Withholding penalty.** Wallets that bridged everything out shortly after each use are scored down.
- **Sybil filter.** Wallets in known farming clusters are excluded or capped.
- **NFT or governance participation.** Voting on proposals or holding the protocol''s NFTs often gets a multiplier.

## Examples worth studying

- **Uniswap UNI (Sep 2020)**: 400 UNI to every wallet that had ever used Uniswap. ~$1,200 at distribution, $5K+ at peak. Pure flat-rate retroactive.
- **ENS (Nov 2021)**: Allocation based on time-weighted name ownership. Subdomains counted. Most generous retroactive of the cycle.
- **LayerZero ZRO (Jun 2024)**: Heavy sybil filtering — about 60% of wallets that were flagged received nothing. Surviving wallets received $300-$30K depending on activity diversity.
- **Wormhole W (Apr 2024)**: Cross-chain bridge volume weighted, with bonus for early Solana → EVM users.
- **Jupiter JUP (Jan 2024)**: Solana DEX, distributed to wallets that had >$1k cumulative trading volume. Median allocation around $1,200.

## Strategy: maximize exposure, minimize farming

If retroactive drops are the highest-EV category, the rational approach is to *be a genuine user* of many high-quality tokenless protocols. Not to farm them. Concretely:

1. Maintain real LP, real lending positions, real NFT holdings across 5-15 protocols you''ve genuinely chosen for product reasons.
2. Avoid the temptation to script transactions. Real-user behavior is the signal you want.
3. Be patient — retroactive drops typically land 12-36 months after a protocol''s launch.
4. Track tokenless protocols via this site or DefiLlama. When one announces a token, check the [/check page](/check) — your wallet may already qualify.

## Bottom line

A retroactive airdrop rewards past usage. They consistently produce the largest payouts and are the hardest to farm. The way to win them is to be a real user of many high-quality protocols — and then let time do the work.', '2026-04-15') ON DUPLICATE KEY UPDATE title=VALUES(title), excerpt=VALUES(excerpt), body_md=VALUES(body_md), published_at=VALUES(published_at);

-- visit_codes (exchange + tool affiliate stubs)
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('binance', 'https://accounts.binance.com/register?ref=REPLACE_ME', NULL, 'binance-ref') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('bybit', 'https://www.bybit.com/invite?ref=REPLACE_ME', NULL, 'bybit-ref') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('okx', 'https://www.okx.com/join/REPLACE_ME', NULL, 'okx-ref') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('mexc', 'https://www.mexc.com/register?inviteCode=REPLACE_ME', NULL, 'mexc-ref') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('kraken', 'https://www.kraken.com/sign-up?ref=REPLACE_ME', NULL, 'kraken-ref') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('rabby', 'https://rabby.io/', NULL, 'rabby-tool') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('revoke', 'https://revoke.cash/', NULL, 'revoke-tool') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);

-- known_airdrop_contracts (with bootstrap airdrops for /check demos)
INSERT INTO airdrops (slug, name, token_symbol, short_description, status, chain_id, category_id, primary_source_id, kyc_required, funding_raised_usd, estimated_value_usd_min, estimated_value_usd_max, social_score, project_url, started_at, end_date) VALUES ('arbitrum-arb-retroactive-demo', 'Arbitrum (ARB) — Retroactive (historical demo)', 'ARB', 'March 2023 ARB retroactive airdrop. Demo entry — the distributor''s claim window has closed, but unclaimed allocations still show as ''eligible'' until the contract is fully swept. Useful as a sanity-check that the checker''s RPC + contract-read pipeline works.', 'ended', (SELECT id FROM chains WHERE slug = 'arbitrum' LIMIT 1), (SELECT id FROM categories WHERE slug = 'retroactive' LIMIT 1), (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1), 0, NULL, 500, 12000, NULL, 'https://arbitrum.foundation', '2023-03-23', '2023-09-23') ON DUPLICATE KEY UPDATE short_description=COALESCE(VALUES(short_description), short_description), status=VALUES(status), estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max);
DELETE FROM known_airdrop_contracts WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'arbitrum-arb-retroactive-demo' LIMIT 1) AND chain_id = (SELECT id FROM chains WHERE slug = 'arbitrum' LIMIT 1) AND LOWER(contract_addr) = LOWER('0x67a24CE4321aB3aF51c2D0a4801c3E111D88C9d9');
INSERT INTO known_airdrop_contracts (airdrop_id, chain_id, contract_addr, method, snapshot_block, claim_url, notes) VALUES ((SELECT id FROM airdrops WHERE slug = 'arbitrum-arb-retroactive-demo' LIMIT 1), (SELECT id FROM chains WHERE slug = 'arbitrum' LIMIT 1), '0x67a24CE4321aB3aF51c2D0a4801c3E111D88C9d9', 'claimable-view', NULL, 'https://arbitrum.foundation/eligibility', 'Arbitrum Foundation token-distributor. Exposes claimableTokens(address). Wallets that never claimed still return > 0 here.');

