-- freecrypto.net — seed data dump
-- Generated by scripts/seed-to-sql.ts; regenerate with `npm run seed:sql`
-- Safe to re-run: every INSERT is idempotent via UNIQUE keys + ON DUPLICATE KEY UPDATE.
SET NAMES utf8mb4;

-- chains
INSERT INTO chains (slug, name, description, sort_order) VALUES ('ethereum', 'Ethereum', 'Original smart-contract chain. Most airdrops still anchor here for L2 retroactives.', 10) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('solana', 'Solana', 'High-throughput L1 with an active airdrop ecosystem (Jupiter, Drift, Kamino, Jito).', 20) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('base', 'Base', 'Coinbase L2 with strong consumer-app traction and no native token (yet).', 30) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('arbitrum', 'Arbitrum', 'Optimistic L2; protocols deployed here remain top airdrop hunting ground.', 40) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('optimism', 'Optimism', 'OP Stack chain with recurring Merit-based airdrop rounds.', 50) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('scroll', 'Scroll', 'zkEVM L2; protocols on it are points-heavy pre-TGE.', 60) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('linea', 'Linea', 'ConsenSys zkEVM, MetaMask-integrated, no native token announced.', 70) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('berachain', 'Berachain', 'Proof-of-Liquidity L1; testnet activity points are tracked for genesis distribution.', 80) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('monad', 'Monad', 'Parallel-EVM L1 in testnet phase; testnet usage may qualify for genesis allocation.', 90) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('sui', 'Sui', 'Move-based L1 with periodic ecosystem incentive programs.', 100) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('ton', 'TON', 'Telegram-native chain; tap-to-earn and mini-app airdrops are concentrated here.', 110) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO chains (slug, name, description, sort_order) VALUES ('starknet', 'Starknet', 'Cairo-based zkRollup; protocols deployed here remain in points phase.', 120) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);

-- categories
INSERT INTO categories (slug, name, description, sort_order) VALUES ('retroactive', 'Retroactive', 'Drops that reward past on-chain activity — usually announced after a snapshot. The highest-EV category historically.', 10) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('testnet', 'Testnet', 'Active incentivized testnets where on-chain tasks accrue points convertible to a future token.', 20) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('points', 'Points', 'Live points programs (Eigen, Ether.fi, Renzo, Pendle YT etc.) where points are expected to convert to tokens.', 30) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('holder', 'Holder', 'Hold-to-earn drops: holders of a specific NFT or token at snapshot qualify automatically.', 40) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('task', 'Task-based', 'Galxe-style quest campaigns: complete on-chain or social tasks for whitelist or guaranteed allocation.', 50) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('exchange', 'Exchange', 'Centralized exchange Launchpool / Megadrop / HODLer style drops (Binance, Bybit, OKX, MEXC).', 60) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);
INSERT INTO categories (slug, name, description, sort_order) VALUES ('telegram', 'Telegram', 'TON-native tap-to-earn and Telegram mini-app airdrops.', 70) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);

-- sources
INSERT INTO sources (slug, name, url) VALUES ('editorial', 'freecrypto.net editorial', 'https://freecrypto.net') ON DUPLICATE KEY UPDATE name=VALUES(name), url=VALUES(url);
INSERT INTO sources (slug, name, url) VALUES ('defillama', 'DefiLlama Airdrops', 'https://defillama.com/airdrops') ON DUPLICATE KEY UPDATE name=VALUES(name), url=VALUES(url);
INSERT INTO sources (slug, name, url) VALUES ('cryptorank', 'CryptoRank Drophunting', 'https://cryptorank.io/drophunting') ON DUPLICATE KEY UPDATE name=VALUES(name), url=VALUES(url);
INSERT INTO sources (slug, name, url) VALUES ('airdropalert', 'AirdropAlert', 'https://airdropalert.com') ON DUPLICATE KEY UPDATE name=VALUES(name), url=VALUES(url);
INSERT INTO sources (slug, name, url) VALUES ('coinmarketcap', 'CoinMarketCap Airdrops', 'https://coinmarketcap.com/airdrop') ON DUPLICATE KEY UPDATE name=VALUES(name), url=VALUES(url);

-- airdrops + per-airdrop visit_codes + faqs
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'monad-genesis', 'Monad', 'MON', NULL, 'Parallel-EVM L1 in public testnet phase. On-chain activity is being tracked for the genesis distribution.',
      'Monad is a high-throughput EVM-compatible L1 that introduces parallel execution and a custom consensus stack. It raised $244M led by Paradigm at a $3B valuation, putting it firmly in the highest-tier-funded testnet of the cycle. The public testnet went live in February 2026 and an explicit testnet incentive program has been hinted at by the team. While no formal airdrop has been confirmed, every team in this funding bracket (Berachain, Eclipse, MegaETH) has historically rewarded testnet usage at genesis. Activity that is most likely to be weighted: native MON-T transactions, deposits to major testnet DEXes, NFT mints on Monad-native marketplaces, validator delegations, and bridge usage.', '- Have a funded testnet wallet (request from the official faucet, not third parties)
- Complete at least 30 unique daily transactions over a 60-day window
- Use the canonical Monad testnet bridge at least 3 times
- Provide liquidity on at least one testnet DEX (Ambient, Apriori, etc.) for >7 days
- Mint at least one NFT from a Monad-native collection
- Avoid sybil patterns: do not fund multiple wallets from the same source', '1. Visit https://testnet.monad.xyz and connect a fresh wallet — do not reuse a wallet that has touched known sybil farms.
2. Request MON-T from the official faucet (rate-limited; daily drips).
3. Bridge testnet ETH from Sepolia via the canonical bridge.
4. Use Ambient or Apriori for at least 3 swaps per week.
5. Provide LP for 7+ days on a stable pair.
6. Watch the official Monad blog for the genesis snapshot announcement — claim portal will go live there.',
      'potential',
      (SELECT id FROM chains WHERE slug = 'monad' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'testnet' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 244000000,
      200, 5000, 92,
      'https://monad.xyz', 'https://x.com/monad_xyz', 'https://discord.gg/monad',
      'y3A6LMDK',
      '2026-02-19', NULL, '2026-08-31'
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('y3A6LMDK', 'https://monad.xyz', (SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1), 0, 'Has Monad confirmed an airdrop?', 'No formal confirmation. The team has acknowledged that testnet activity will be considered for genesis distribution but has not promised a specific allocation.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1), 1, 'How do I avoid sybil filters?', 'Use a single wallet per identity, do not fund from the same CEX address across multiple wallets, and create genuine usage patterns (real LP, real swaps, varied timing). Monad''s team has stated they will analyze on-chain heuristics aggressively.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1), 2, 'Is KYC required?', 'No KYC is expected for the genesis claim. Subsequent CEX listings may impose KYC at the exchange level.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'monad-genesis' LIMIT 1), 3, 'When is the snapshot?', 'Unannounced. Expect a snapshot 2-4 weeks before mainnet launch, which is currently targeted for late 2026.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'megaeth-testnet', 'MegaETH', 'MEGA', NULL, 'Real-time blockchain claiming sub-10ms block times; public testnet open with explicit user-activity tracking.',
      'MegaETH is positioning itself as the first ''real-time'' EVM rollup, with sub-10ms preconfirmations and 100,000+ TPS targets. The project raised $30M with backing from Dragonfly, Robot Ventures, and Vitalik Buterin personally, and went live with a public testnet in March 2026. The team has confirmed that public testnet activity will be a meaningful input to the eventual token distribution, making this one of the cleaner testnet farming opportunities in the cycle. Trading, lending, and NFT-mint activity on testnet-native dapps (Cap, GTE, Ducks) are all being indexed.', '- Bridge testnet ETH to MegaETH via the canonical bridge
- Use at least 3 different testnet-native dapps
- Maintain a 30+ day activity streak
- Hold a positive MegaETH testnet balance at the eventual snapshot
- Engage with at least one perp DEX (GTE) or money market (Cap)', '1. Connect a wallet at testnet.megaeth.com and request testnet ETH from the faucet.
2. Bridge from Sepolia using the canonical bridge.
3. Place at least 5 trades on GTE per week.
4. Lend or borrow on Cap testnet (low value is fine).
5. Mint one Ducks testnet NFT.
6. Claim portal will be announced post-mainnet — do not connect to any ''MegaETH airdrop claim'' site before the official announcement.',
      'potential',
      (SELECT id FROM chains WHERE slug = 'ethereum' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'testnet' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 30000000,
      300, 8000, 88,
      'https://megaeth.com', 'https://x.com/megaeth_labs', NULL,
      'sGUN0mtz',
      '2026-03-06', NULL, '2026-09-30'
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('sGUN0mtz', 'https://megaeth.com', (SELECT id FROM airdrops WHERE slug = 'megaeth-testnet' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'megaeth-testnet' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'megaeth-testnet' LIMIT 1), 0, 'Is the testnet open to anyone?', 'Yes — anyone can access testnet.megaeth.com without an invite as of Q1 2026.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'megaeth-testnet' LIMIT 1), 1, 'What is the expected mainnet date?', 'Team has not committed publicly. Most signals point to Q4 2026 / Q1 2027.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'megaeth-testnet' LIMIT 1), 2, 'How is testnet usage measured?', 'MegaETH has not published the exact scoring formula. Expect diversity of dapps used, total transactions, and recency to all matter.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'berachain-bgt-boost', 'Berachain BGT Boost', 'BGT', NULL, 'Boost validators with your BGT to earn protocol-level emissions across Berachain''s Proof-of-Liquidity ecosystem.',
      'Berachain''s Proof-of-Liquidity consensus issues BGT (governance) to LPs in whitelisted pools. Holders can then ''boost'' validators with their BGT, which directs subsequent emissions to chosen reward vaults. The BGT Boost program rewards consistent boosters with weekly USDC + ecosystem token drops from validator-funded incentive pools. Several Berachain-native protocols (Infrared, BeraBorrow, Honeypot) co-incentivize on top, layering additional yield. Boost positions can be modified weekly. Total emissions are several hundred thousand dollars per week across the validator set.', '- Acquire BGT by providing liquidity in any whitelisted BPL pool
- Delegate (Boost) your BGT to at least one active validator
- Hold the boost position across at least one full weekly epoch
- Optionally: layer with Infrared or BeraBorrow for additional yield', '1. Go to hub.berachain.com and connect a wallet.
2. Provide liquidity in a BPL pool (e.g. HONEY/BERA on BEX).
3. Stake the LP tokens in the reward vault to begin earning BGT.
4. Delegate accumulated BGT to a validator via the Boost screen.
5. Claim rewards every Monday from the Rewards tab.
6. Re-stake or rotate to higher-APR validators as incentives shift.',
      'confirmed',
      (SELECT id FROM chains WHERE slug = 'berachain' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'points' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 142000000,
      100, 3500, 84,
      'https://berachain.com', 'https://x.com/berachain', 'https://discord.gg/berachain',
      'SuMmSuC9',
      '2026-02-06', NULL, '2026-07-15'
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('SuMmSuC9', 'https://berachain.com', (SELECT id FROM airdrops WHERE slug = 'berachain-bgt-boost' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'berachain-bgt-boost' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'berachain-bgt-boost' LIMIT 1), 0, 'Is BGT transferable?', 'No — BGT is soulbound to the wallet that earned it. It can only be redeemed for BERA or used to boost validators.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'berachain-bgt-boost' LIMIT 1), 1, 'What is the minimum to participate?', 'There is no hard minimum but expect gas + ~$50 in LP to make rewards meaningful.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'berachain-bgt-boost' LIMIT 1), 2, 'Are rewards taxable?', 'In most jurisdictions yes — boost emissions are treated as ordinary income at receipt. Consult a tax professional.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'sonic-airdrop-s2', 'Sonic Labs Points Season 2', 'S', NULL, 'Sonic''s S2 points program rewards activity on its high-speed EVM chain. Snapshot mid-September.',
      'Following S1''s $250M+ distribution, Sonic Labs has opened Season 2 of its points program. Points are earned for bridging assets, providing liquidity in whitelisted Sonic Gateway pools, and using Sonic-native dapps (SwapX, Beethoven X, Silo Finance V2). The S2 conversion ratio has been pre-announced at 200 points = 1 S token, with a hard cap on per-wallet allocations to combat sybils. Activity from S1 is not carried over — wallets must accrue fresh S2 points.', '- Bridge to Sonic via the official Gateway
- Accumulate points by holding stablecoins (1 pt / $ / day) or whitelisted LPs (2.5 pts / $ / day)
- Use SwapX or Beethoven X for at least 3 swaps per week
- Minimum 50,000 points required to qualify', '1. Bridge ETH or USDC to Sonic via https://gateway.soniclabs.com.
2. Park balance in a points-eligible vault — staked S, Silo USDC vault, etc.
3. Add LP on SwapX for the highest per-dollar rate.
4. Track your points via the official dashboard.
5. Snapshot is September 15, 2026 — keep position live until then.
6. Tokens will be claimable via the same dashboard 1-2 weeks after snapshot.',
      'live',
      (SELECT id FROM chains WHERE slug = 'ethereum' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'points' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 0,
      150, 4000, 76,
      'https://sonic.fan', 'https://x.com/0xSonicLabs', NULL,
      'esrMVhyB',
      '2026-04-01', '2026-09-15', '2026-09-30'
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('esrMVhyB', 'https://sonic.fan', (SELECT id FROM airdrops WHERE slug = 'sonic-airdrop-s2' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'sonic-airdrop-s2' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'sonic-airdrop-s2' LIMIT 1), 0, 'Did S1 actually distribute?', 'Yes — Sonic''s S1 distributed in early 2026 and trades on most major exchanges. S2 conditions are similar.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'sonic-airdrop-s2' LIMIT 1), 1, 'Is there a per-wallet cap?', 'Yes — the team has indicated a soft cap around 1M points per wallet. Beyond that the marginal allocation tapers significantly.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'symbiotic-points', 'Symbiotic', NULL, NULL, 'Permissionless restaking primitive backed by Paradigm. Deposit-cap based points program is live.',
      'Symbiotic is a generalized restaking protocol that competes with EigenLayer by allowing any asset (not just ETH derivatives) to back AVS-style services. Backed by Paradigm with strong DeFi integrations (Mellow, Ether.fi, Pendle), the protocol''s points program rewards depositors with ''Symbiotic Points'' that are widely expected to convert at TGE. Deposits have been cap-gated, with multiple raises being filled within hours, indicating high pre-TGE demand.', '- Deposit a supported asset (wstETH, cbETH, swETH, sUSDe) into Symbiotic vaults
- Maintain the position across at least one weekly epoch
- Optionally route through Mellow or Ether.fi for boosted multipliers', '1. Visit app.symbiotic.fi.
2. Connect a wallet holding a supported asset.
3. Deposit into an available vault (subject to caps — refresh when caps open).
4. Optionally migrate to a Mellow vault for additional point multiplier.
5. Points are tracked on-chain and on the dashboard. Claim portal will be announced.',
      'live',
      (SELECT id FROM chains WHERE slug = 'ethereum' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'points' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 5800000,
      100, 6000, 81,
      'https://symbiotic.fi', 'https://x.com/symbioticfi', NULL,
      'IrupFfTk',
      '2026-01-15', NULL, NULL
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('IrupFfTk', 'https://symbiotic.fi', (SELECT id FROM airdrops WHERE slug = 'symbiotic-points' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'symbiotic-points' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'symbiotic-points' LIMIT 1), 0, 'What''s the conversion rate?', 'Not announced. Comparable protocols (EigenLayer, Ether.fi) saw 0.1–1% of point value distributed at TGE.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'symbiotic-points' LIMIT 1), 1, 'Can I withdraw early?', 'Yes, but exiting before snapshot forfeits accumulated multipliers.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'polymarket-trader-drop', 'Polymarket Trader Rewards', NULL, NULL, 'Polymarket''s recent funding round and US-relisting put a token launch firmly on the table. Active traders are the obvious airdrop target.',
      'Polymarket completed a $200M+ funding round in early 2026 and re-entered the US market via QCX acquisition. Vitalik Buterin and Anthropic founders have publicly endorsed the platform. While the team has not committed to a token, the combination of regulatory clarity, large funding, and competitor (Kalshi) momentum suggests a token launch is increasingly likely. Volume traders are the highest-probability beneficiaries. Geographic eligibility may vary at TGE.', '- Trade on Polymarket regularly (minimum ~$100/month volume historically used by similar protocols)
- Maintain a positive USDC.e balance on Polygon
- US users: Polymarket now accepts US traders post-QCX; jurisdiction may still affect token eligibility', '1. Sign up at polymarket.com (KYC may be required for US users).
2. Deposit USDC to your Polymarket account.
3. Trade across diverse markets — political, sports, crypto. Diversity historically scores higher than volume in single market.
4. Continue trading through any pre-announced snapshot window.
5. Watch official channels — fake claim sites are extremely common for Polymarket; verify URLs.',
      'potential',
      (SELECT id FROM chains WHERE slug = 'ethereum' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'task' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 70000000,
      500, 10000, 95,
      'https://polymarket.com', 'https://x.com/Polymarket', NULL,
      'w284ty4w',
      '2026-05-01', NULL, NULL
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('w284ty4w', 'https://polymarket.com', (SELECT id FROM airdrops WHERE slug = 'polymarket-trader-drop' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'polymarket-trader-drop' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'polymarket-trader-drop' LIMIT 1), 0, 'Is a Polymarket token confirmed?', 'No. But the structural setup (large raise, US relisting, growing volume) mirrors every prior crypto-native platform that issued a token within 12-18 months.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'polymarket-trader-drop' LIMIT 1), 1, 'Will US users qualify?', 'Unknown. Token-distribution geographic restrictions are separate from trading-platform restrictions and Polymarket has not commented.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'walrus-storage-testnet', 'Walrus', 'WAL', NULL, 'Mysten Labs'' decentralized blob storage on Sui — testnet stakers and storage users are tracked for the WAL drop.',
      'Walrus is a decentralized storage protocol built on Sui by Mysten Labs (the team behind Sui itself). It uses erasure coding (Red Stuff) to store large blobs at significantly lower cost than competitors like Filecoin or Arweave. The team has confirmed a WAL token launch and an initial community distribution targeting testnet storage users, validators, and Sui ecosystem participants. Snapshot is June 30 2026.', '- Hold and stake SUI through a Walrus-eligible validator
- Upload at least 100MB of test blobs to the Walrus testnet
- Run a Walrus storage node (advanced — Linux required)', '1. Acquire SUI on a CEX or DEX and bridge to Sui mainnet.
2. Visit walrus.xyz and connect a Sui wallet.
3. Upload test data via the Walrus CLI or UI.
4. Wait for snapshot, then claim on the official portal after TGE.',
      'confirmed',
      (SELECT id FROM chains WHERE slug = 'sui' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'testnet' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 13000000,
      80, 1500, 72,
      'https://walrus.xyz', 'https://x.com/WalrusProtocol', NULL,
      'fAmI53aS',
      '2026-03-15', '2026-06-30', '2026-07-15'
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('fAmI53aS', 'https://walrus.xyz', (SELECT id FROM airdrops WHERE slug = 'walrus-storage-testnet' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'walrus-storage-testnet' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'walrus-storage-testnet' LIMIT 1), 0, 'Is the WAL drop confirmed?', 'Yes — Mysten Labs has formally announced WAL with an explicit community distribution component.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'humanity-protocol-genesis', 'Humanity Protocol', 'H', NULL, 'Palm-scan biometric proof-of-humanity. KYC-style verification required, but verified humans earn daily H credits.',
      'Humanity Protocol uses palm-vein recognition to issue sybil-resistant proof-of-personhood credentials, competing directly with Worldcoin. Verified users earn daily H token credits convertible at TGE. Because the verification is biometric, KYC-style data is collected — this is the major caveat for privacy-conscious users.', '- Verify with a Humanity Protocol Verifier (in-app palm scan)
- Open the app daily to claim H credits
- Refer additional verified humans for boosted credits', '1. Install the Humanity Protocol app from your phone''s app store.
2. Complete the palm-vein verification at a Verifier (in-person required in some regions).
3. Open the app every 24h to claim accruing H credits.
4. Claim portal will activate at TGE; tokens issued to the verified address.',
      'live',
      (SELECT id FROM chains WHERE slug = 'ethereum' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'task' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      1, 32000000,
      50, 1200, 68,
      'https://humanity.org', 'https://x.com/Humanityprot', NULL,
      'dvrAHooO',
      '2026-02-01', NULL, '2026-12-31'
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('dvrAHooO', 'https://humanity.org', (SELECT id FROM airdrops WHERE slug = 'humanity-protocol-genesis' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'humanity-protocol-genesis' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'humanity-protocol-genesis' LIMIT 1), 0, 'Is biometric data stored?', 'Humanity Protocol claims biometric data is processed locally and only a zero-knowledge commitment is stored on-chain. Critics dispute the strength of these guarantees.');
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'humanity-protocol-genesis' LIMIT 1), 1, 'Is this safe for me?', 'Only you can decide. Biometric data, once leaked, cannot be reset. We provide no recommendation either way.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'linea-surge-points', 'Linea Surge', NULL, NULL, 'ConsenSys''s zkEVM has no token yet. Linea Surge LXP-L points and ecosystem TVL programs are the most likely qualifier paths.',
      'Linea is ConsenSys''s zkEVM rollup. It has not yet announced a native token, but the team runs an active points program (LXP-L) tied to provable on-chain actions and a ''Surge'' program tied to TVL bridged into Linea-native DeFi (Lynex, Mendi, etc.). MetaMask-native integration positions Linea for a large eventual user base.', '- Bridge ETH to Linea via the canonical bridge
- Provide liquidity in Linea Surge-eligible pools
- Hold LXP and LXP-L points (earned through Galxe quests and on-chain activity)', '1. Bridge ETH at bridge.linea.build.
2. Complete monthly Galxe quests at linea.build/hub.
3. Provide LP in Lynex or Mendi.
4. Watch for the eventual token announcement.',
      'potential',
      (SELECT id FROM chains WHERE slug = 'linea' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'points' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 0,
      100, 3000, 70,
      'https://linea.build', 'https://x.com/LineaBuild', NULL,
      'P9f0drU3',
      '2026-01-10', NULL, NULL
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('P9f0drU3', 'https://linea.build', (SELECT id FROM airdrops WHERE slug = 'linea-surge-points' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'linea-surge-points' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'linea-surge-points' LIMIT 1), 0, 'Has Linea confirmed a token?', 'No. Joseph Lubin (ConsenSys) has hedged on the question publicly but the LXP/LXP-L point design strongly resembles a pre-TGE accumulation system.');
INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      'tapswap-season-3', 'TapSwap Season 3', 'TAPS', NULL, 'Telegram tap-to-earn mini-app, S3 cohort. Low effort, low EV — but qualifying takes 5 minutes a day.',
      'TapSwap is a Telegram-native tap-to-earn game on TON. S1 distributed real tokens; S2 was modest; S3 is now active. Expected value per wallet is small ($5-$50 typical) but the time investment is correspondingly low. Useful as a ''free shot'' in a diversified airdrop strategy.', '- Have a Telegram account in good standing (not freshly created)
- Mine taps daily and complete the daily checklist
- Connect a TON wallet (Tonkeeper or similar) for claim', '1. Open https://t.me/tapswap_bot inside Telegram.
2. Mine taps each day until energy depletes.
3. Complete the daily quests for boosters.
4. Connect a TON wallet before snapshot.
5. Claim is automatic to the connected wallet post-snapshot.',
      'live',
      (SELECT id FROM chains WHERE slug = 'ton' LIMIT 1),
      (SELECT id FROM categories WHERE slug = 'telegram' LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      0, 0,
      5, 200, 60,
      'https://tapswap.club', 'https://x.com/tapswap_mining', NULL,
      '_hETRvQx',
      '2026-04-10', '2026-07-20', '2026-07-31'
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('_hETRvQx', 'https://tapswap.club', (SELECT id FROM airdrops WHERE slug = 'tapswap-season-3' LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);
DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'tapswap-season-3' LIMIT 1);
INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = 'tapswap-season-3' LIMIT 1), 0, 'Are tap-to-earn drops worth my time?', 'Marginally. Expect $5-$50 for 5 min/day over a few months. Skip if your time is worth more than that hourly.');

-- guides
INSERT INTO guides (slug, title, excerpt, body_md, published_at) VALUES ('avoid-connect-wallet-airdrop-scams', 'How to avoid the "connect wallet to verify" airdrop scam (2026 update)', 'Pasting a public address to check airdrop eligibility is safe. Signing a transaction to ''verify'' your wallet is how almost every airdrop draining attack of 2024-2026 started. Here''s exactly what to watch for.', '## Why this matters

The single biggest financial risk in the airdrop space is not picking the wrong project — it''s getting drained by a fake checker site. Throughout 2024, 2025, and into 2026, the dominant attack pattern has stayed identical: lure users to a fake "airdrop checker" or "claim portal" with a Google Ad or Twitter reply, ask them to "connect wallet to verify eligibility," then drain everything in the wallet via a hidden malicious signature.

The attack is so durable because the user-facing prompt looks identical to a legitimate dapp interaction. If you understand exactly what is happening under the hood, the warning signs become obvious.

## What "connect wallet" actually does

Connecting a wallet to a site does NOT, on its own, give the site any power to move your funds. Connection only shares your public address. The site needs you to *sign* something to do anything malicious.

The danger is in the very next prompt that almost always follows. The site will request one of these signature types:

- `permit` or `permit2` — gives the site permission to spend a specific token without a separate approval transaction. One signature, your stablecoins are gone.
- `setApprovalForAll` — gives blanket NFT spend rights. Your Bored Ape is gone in the next block.
- A swap or transfer transaction that has been crafted to drain a specific token.

Legitimate airdrop checkers DO NOT need any of these signatures. Pasting a public address is enough to query the blockchain.

## The cardinal rule

> If a site asks you to sign anything to *check* eligibility, close the tab.

The only signature that should appear during a real airdrop flow is the actual **claim transaction**, after the snapshot, on the project''s official URL. And even then, simulate it in a wallet that supports transaction simulation (Rabby, Frame, OneKey) before approving.

## How to verify a checker is safe

1. **URL check.** Type the official URL by hand. Never click a link from a reply, DM, or sponsored search result. Bookmark legit sites the first time you visit.
2. **No connection prompt.** A safe checker has a text input for an address. That''s it. No "Connect Wallet" button on the checker page.
3. **Read-only confirmation.** The checker explicitly states it does not request signatures. (Ours does — see the [/check page](/check).)
4. **No urgency.** Real airdrops do not have "claim in the next 5 minutes or lose forever" timers. Anything that pressures speed is a phish.

## Wallet hygiene if you farm airdrops

- Use a **fresh wallet** with no other funds for any interaction with a new dapp.
- After confirming a dapp is safe, you can graduate it to your "farming" wallet with small balances.
- **Never** sign anything from your main wallet that holds long-term assets.
- Use a **hardware wallet** for the main vault. The cost is $80; the upside is a drainer can''t pull funds without physical confirmation.
- Revoke approvals quarterly via [revoke.cash](https://revoke.cash).

## What to do if you''ve already signed something suspicious

1. Move every asset out of the affected wallet immediately to a fresh wallet — gas willing.
2. Revoke all approvals on revoke.cash (this may not save you if a `permit` was already used to transfer).
3. Report the phish on Twitter / Telegram so others avoid it.
4. Assume the wallet is permanently compromised. Never use it again, even after revoking.

## Bottom line

Paste, don''t sign. Every credible airdrop checker — including this one — works on public addresses alone. Treat any prompt for a signature during eligibility verification as definitive proof you''re on a phishing site, and close the tab.', '2026-05-10') ON DUPLICATE KEY UPDATE title=VALUES(title), excerpt=VALUES(excerpt), body_md=VALUES(body_md), published_at=VALUES(published_at);
INSERT INTO guides (slug, title, excerpt, body_md, published_at) VALUES ('how-to-qualify-for-l2-airdrops-2026', 'How to qualify for L2 airdrops in 2026 (without sybil flagging)', 'A practical playbook for farming L2 airdrops that survive the inevitable sybil filter. Diversity beats volume; consistency beats burst farming; and unique behavioral signatures beat bot-perfect activity.', '## What changed in 2026

The ZK-rollup wave of 2024-2025 (zkSync, Starknet, Linea, Scroll) trained teams how to filter sybils aggressively. Every major L2 airdrop since LayerZero has applied multi-axis sybil detection: address-graph clustering, behavioral fingerprinting, fund-source analysis, and timing distribution. Pre-2024 farming techniques (50-wallet stamping, identical-amount transactions, same-day funding) are now reliably filtered out.

The modern L2 airdrop is best understood as **a behavioral pattern recognition contest, not a volume contest**. You are trying to look like a real user who happens to use multiple wallets, not a farmer.

## The signals that matter

From every published sybil-detection methodology (Hop Protocol''s, LayerZero''s, Optimism''s), these are the axes graders use:

1. **Funding source diversity.** Wallets funded from the same CEX address within the same hour are clustered. Use different CEXes, different times, different amounts. Better: peer-to-peer funding from a fresh wallet you control, mixed with CEX withdrawals.
2. **Time distribution.** Real users don''t transact in 5-minute bursts on 30 wallets. Spread activity across days and weeks, with natural gaps.
3. **Dapp diversity.** Touching only the bridge marks you as a farmer. Real users swap, lend, mint NFTs, vote, and bridge.
4. **Transaction value variance.** All your txs being $10 ± $1 is a red flag. Real value distributions are skewed and noisy.
5. **Gas pattern.** Submitting only at minimum priority fee marks you. Sometimes overpay; sometimes wait.
6. **Holding behavior.** Bridge → swap → bridge back same day = farmer. Bridge → keep position for weeks = user.

## The minimum viable strategy

For any active L2 with a likely retroactive drop:

- **30+ days** between first activity and snapshot. Anything shorter is increasingly filtered.
- **3+ unique dapps** touched: bridge + DEX + lending or NFT.
- **5-15 transactions/month** across those dapps. Quality over quantity.
- **Maintain a non-trivial position** (e.g., $50+ LP, $100+ lent) across the snapshot.
- **Do something native to the chain** — a Linea-only protocol, a Base-only mint, a Scroll-only social app. Generic protocols deployed everywhere are deprioritized.

## Wallet count tradeoff

1 wallet that looks like a real user beats 20 wallets that look like farmers. If you must run multiples:

- Maximum 3-5 wallets across an L2.
- Each wallet funded from a different source.
- Each wallet''s behavioral profile materially different (one heavy DEX, one heavy lending, one heavy NFT).
- No common withdrawal address pre-snapshot.

More than 5 wallets per L2 is a losing strategy in 2026.

## Chains worth farming right now

At time of writing (May 2026):

- **Monad** — testnet active, no token, $244M raised, very likely retroactive.
- **MegaETH** — testnet active, team has confirmed activity will be counted.
- **Linea** — LXP/LXP-L points active, ConsenSys has not committed to a token but the system is designed like a pre-TGE accumulation.
- **Berachain** — mainnet live, BGT boost emissions are paying out weekly.
- **Sonic** — Season 2 points open through September 2026 snapshot.

See the [/check page](/check) to test whether any wallets you''ve already used would qualify for finalized snapshots.

## What kills your allocation

- **Funding from a sanctioned mixer.** Allocation goes to zero. Use clean funds.
- **Behavioral clustering with known farms.** If your wallet''s behavior matches a published sybil cluster, you''re cut.
- **Trading exclusively with yourself.** Wash trades across your own wallets are detected by every modern grader.
- **Activity ending exactly at snapshot.** A natural user keeps using the chain after the airdrop too. Many graders include a post-snapshot continuation check.

## Bottom line

Farming L2 airdrops profitably in 2026 means looking like a real user who has multiple wallets, not a farmer trying to look like a real user. The fewer wallets, the more diverse the behavior, the longer the timeline, the higher the expected value per wallet.', '2026-04-28') ON DUPLICATE KEY UPDATE title=VALUES(title), excerpt=VALUES(excerpt), body_md=VALUES(body_md), published_at=VALUES(published_at);
INSERT INTO guides (slug, title, excerpt, body_md, published_at) VALUES ('what-is-a-retroactive-airdrop', 'What is a retroactive airdrop? (And why they''re the highest-EV category)', 'A retroactive airdrop rewards on-chain activity that already happened before the token was announced. They consistently produce the largest per-wallet payouts — but only for users who happened to use the protocol naturally, which is the catch.', '## Definition

A retroactive airdrop distributes tokens to wallets that interacted with a protocol *before* the token was announced. The protocol team takes an on-chain snapshot of historical users, applies a scoring formula, and allocates tokens proportionally.

Key distinction from other airdrop types:

- **Retroactive** rewards past activity. You qualify by accident, by being an early user. Examples: Uniswap (UNI, 2020), 1inch, dYdX V2, ENS, Arbitrum (ARB), Optimism (OP), LayerZero (ZRO), Wormhole (W), Jupiter (JUP).
- **Points / live programs** reward present activity. You qualify by participating in a known points system. Examples: EigenLayer points, Ether.fi loyalty, Pendle YT.
- **Testnet** rewards activity on a chain''s testnet pre-mainnet. Examples: Aptos, Sui, ZK-Sync (partially), Monad (upcoming).
- **Task-based** rewards completing a defined quest, usually via Galxe or Zealy.

## Why retroactive drops have the highest historical EV

Three reasons:

1. **Smaller eligible population.** Pre-announcement users are by definition early adopters. The denominator on token-per-wallet is small.
2. **Strong product-market fit signal.** Protocols willing to distribute retroactively typically have real users and revenue — these aren''t vapor coins. The token retains value better.
3. **Lower farming risk.** You can''t farm what hasn''t been announced. The early users qualified through genuine usage, not deliberate gaming, which limits sybil dilution.

**The catch:** by definition, you can''t *target* a future retroactive drop, because they''re not announced. The best you can do is interact with high-quality protocols that *might* tokenize, betting that some of them will reward early activity.

## The retroactive-drop heuristic

Protocols that are most likely to do a retroactive drop tend to:

- Have raised $20M+ from top-tier VCs (Paradigm, a16z, Coinbase Ventures, Polychain).
- Have a tokenless competitor that already tokenized (creates pressure).
- Be deployed for 12+ months with measurable user growth and TVL.
- Have a public Discord with talk of "community ownership" but no token announcement.
- Be on an L2 or L1 that itself rewarded retroactively (Arbitrum, Optimism, Base ecosystem protocols).

DefiLlama''s [airdrops page](https://defillama.com/airdrops) tracks the universe of tokenless protocols — a useful candidate list. We pull from this source for our [home page](/) listings.

## How retroactive scoring usually works

The exact formula is always different, but common ingredients:

- **Time-weighted volume.** Activity that happened earlier in the protocol''s life weighs more.
- **Diversity bonus.** Using multiple features of the protocol scores higher than only using one.
- **Withholding penalty.** Wallets that bridged everything out shortly after each use are scored down.
- **Sybil filter.** Wallets in known farming clusters are excluded or capped.
- **NFT or governance participation.** Voting on proposals or holding the protocol''s NFTs often gets a multiplier.

## Examples worth studying

- **Uniswap UNI (Sep 2020)**: 400 UNI to every wallet that had ever used Uniswap. ~$1,200 at distribution, $5K+ at peak. Pure flat-rate retroactive.
- **ENS (Nov 2021)**: Allocation based on time-weighted name ownership. Subdomains counted. Most generous retroactive of the cycle.
- **LayerZero ZRO (Jun 2024)**: Heavy sybil filtering — about 60% of wallets that were flagged received nothing. Surviving wallets received $300-$30K depending on activity diversity.
- **Wormhole W (Apr 2024)**: Cross-chain bridge volume weighted, with bonus for early Solana → EVM users.
- **Jupiter JUP (Jan 2024)**: Solana DEX, distributed to wallets that had >$1k cumulative trading volume. Median allocation around $1,200.

## Strategy: maximize exposure, minimize farming

If retroactive drops are the highest-EV category, the rational approach is to *be a genuine user* of many high-quality tokenless protocols. Not to farm them. Concretely:

1. Maintain real LP, real lending positions, real NFT holdings across 5-15 protocols you''ve genuinely chosen for product reasons.
2. Avoid the temptation to script transactions. Real-user behavior is the signal you want.
3. Be patient — retroactive drops typically land 12-36 months after a protocol''s launch.
4. Track tokenless protocols via this site or DefiLlama. When one announces a token, check the [/check page](/check) — your wallet may already qualify.

## Bottom line

A retroactive airdrop rewards past usage. They consistently produce the largest payouts and are the hardest to farm. The way to win them is to be a real user of many high-quality protocols — and then let time do the work.', '2026-04-15') ON DUPLICATE KEY UPDATE title=VALUES(title), excerpt=VALUES(excerpt), body_md=VALUES(body_md), published_at=VALUES(published_at);

-- visit_codes (exchange + tool affiliate stubs)
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('binance', 'https://accounts.binance.com/register?ref=REPLACE_ME', NULL, 'binance-ref') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('bybit', 'https://www.bybit.com/invite?ref=REPLACE_ME', NULL, 'bybit-ref') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('okx', 'https://www.okx.com/join/REPLACE_ME', NULL, 'okx-ref') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('mexc', 'https://www.mexc.com/register?inviteCode=REPLACE_ME', NULL, 'mexc-ref') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('kraken', 'https://www.kraken.com/sign-up?ref=REPLACE_ME', NULL, 'kraken-ref') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('rabby', 'https://rabby.io/', NULL, 'rabby-tool') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);
INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES ('revoke', 'https://revoke.cash/', NULL, 'revoke-tool') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);

-- known_airdrop_contracts (with bootstrap airdrops for /check demos)
INSERT INTO airdrops (slug, name, token_symbol, short_description, status, chain_id, category_id, primary_source_id, kyc_required, funding_raised_usd, estimated_value_usd_min, estimated_value_usd_max, social_score, project_url, started_at, end_date) VALUES ('arbitrum-arb-retroactive-demo', 'Arbitrum (ARB) — Retroactive (historical demo)', 'ARB', 'March 2023 ARB retroactive airdrop. Demo entry — the distributor''s claim window has closed, but unclaimed allocations still show as ''eligible'' until the contract is fully swept. Useful as a sanity-check that the checker''s RPC + contract-read pipeline works.', 'ended', (SELECT id FROM chains WHERE slug = 'arbitrum' LIMIT 1), (SELECT id FROM categories WHERE slug = 'retroactive' LIMIT 1), (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1), 0, NULL, 500, 12000, NULL, 'https://arbitrum.foundation', '2023-03-23', '2023-09-23') ON DUPLICATE KEY UPDATE short_description=COALESCE(VALUES(short_description), short_description), status=VALUES(status), estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max);
DELETE FROM known_airdrop_contracts WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = 'arbitrum-arb-retroactive-demo' LIMIT 1) AND chain_id = (SELECT id FROM chains WHERE slug = 'arbitrum' LIMIT 1) AND LOWER(contract_addr) = LOWER('0x67a24CE4321aB3aF51c2D0a4801c3E111D88C9d9');
INSERT INTO known_airdrop_contracts (airdrop_id, chain_id, contract_addr, method, snapshot_block, claim_url, notes) VALUES ((SELECT id FROM airdrops WHERE slug = 'arbitrum-arb-retroactive-demo' LIMIT 1), (SELECT id FROM chains WHERE slug = 'arbitrum' LIMIT 1), '0x67a24CE4321aB3aF51c2D0a4801c3E111D88C9d9', 'claimable-view', NULL, 'https://arbitrum.foundation/eligibility', 'Arbitrum Foundation token-distributor. Exposes claimableTokens(address). Wallets that never claimed still return > 0 here.');

