/**
 * One-off: converts every seeds/*.json into a single SQL file that can be
 * imported via phpMyAdmin in production environments where running
 * `npm run seed` over an SSH tunnel isn't an option.
 *
 * Output: migrations/002_seed_data.sql
 *
 * Usage: npm run seed:sql   (or  tsx scripts/seed-to-sql.ts)
 *
 * Idempotent on re-run via INSERT IGNORE / ON DUPLICATE KEY UPDATE.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, "..");
const SEEDS_DIR = path.join(ROOT, "seeds");
const OUT = path.join(ROOT, "migrations", "002_seed_data.sql");

function esc(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number" && Number.isFinite(v)) return String(v);
  if (typeof v === "boolean") return v ? "1" : "0";
  const s = String(v).replace(/\\/g, "\\\\").replace(/'/g, "''").replace(/\r/g, "");
  return `'${s}'`;
}

function slugify(input: string): string {
  return input.toLowerCase().normalize("NFKD").replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80);
}

function visitCode(slug: string): string {
  const crypto = require("node:crypto") as typeof import("node:crypto");
  return crypto.createHash("sha256").update(`v1:${slug}`).digest("base64url").slice(0, 8);
}

interface ChainSeed { slug: string; name: string; description: string | null; sort_order: number; }
interface CategorySeed { slug: string; name: string; description: string | null; sort_order: number; }
interface SourceSeed { slug: string; name: string; url: string | null; }
interface FaqSeed { question: string; answer_md: string; }
interface AirdropSeed {
  slug: string; name: string; token_symbol: string | null; logo_url: string | null;
  status: string; chain: string; category: string; kyc_required: boolean;
  funding_raised_usd: number | null;
  estimated_value_usd_min: number | null; estimated_value_usd_max: number | null;
  social_score: number | null;
  started_at: string | null; snapshot_date: string | null; end_date: string | null;
  project_url: string | null; twitter_url: string | null; discord_url: string | null;
  short_description: string | null; description_md: string;
  eligibility_md: string; how_to_claim_md: string;
  faqs: FaqSeed[];
}
interface GuideSeed { slug: string; title: string; excerpt: string; body_md: string; published_at: string; }
interface CodeSeed { code: string; target_url: string; source_label: string; notes?: string; }

function readJson<T>(file: string): T {
  return JSON.parse(fs.readFileSync(path.join(SEEDS_DIR, file), "utf8")) as T;
}

const chunks: string[] = [
  "-- freecrypto.net — seed data dump",
  "-- Generated by scripts/seed-to-sql.ts; regenerate with `npm run seed:sql`",
  "-- Safe to re-run: every INSERT is idempotent via UNIQUE keys + ON DUPLICATE KEY UPDATE.",
  "SET NAMES utf8mb4;",
  "",
];

const chains = readJson<ChainSeed[]>("chains.json");
chunks.push("-- chains");
for (const c of chains) {
  chunks.push(
    `INSERT INTO chains (slug, name, description, sort_order) VALUES (${esc(c.slug)}, ${esc(c.name)}, ${esc(c.description)}, ${esc(c.sort_order)}) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);`,
  );
}
chunks.push("");

const categories = readJson<CategorySeed[]>("categories.json");
chunks.push("-- categories");
for (const c of categories) {
  chunks.push(
    `INSERT INTO categories (slug, name, description, sort_order) VALUES (${esc(c.slug)}, ${esc(c.name)}, ${esc(c.description)}, ${esc(c.sort_order)}) ON DUPLICATE KEY UPDATE name=VALUES(name), description=VALUES(description), sort_order=VALUES(sort_order);`,
  );
}
chunks.push("");

const sources = readJson<SourceSeed[]>("sources.json");
chunks.push("-- sources");
for (const s of sources) {
  chunks.push(
    `INSERT INTO sources (slug, name, url) VALUES (${esc(s.slug)}, ${esc(s.name)}, ${esc(s.url)}) ON DUPLICATE KEY UPDATE name=VALUES(name), url=VALUES(url);`,
  );
}
chunks.push("");

// airdrops: upsert by slug; the FK columns reference chain.slug, category.slug
// and source.slug via subqueries so we don't need to know the auto-IDs.
const airdrops = readJson<AirdropSeed[]>("airdrops.json");
chunks.push("-- airdrops + per-airdrop visit_codes + faqs");
for (const a of airdrops) {
  const code = visitCode(a.slug);
  chunks.push(
    `INSERT INTO airdrops (
      slug, name, token_symbol, logo_url, short_description,
      description_md, eligibility_md, how_to_claim_md,
      status, chain_id, category_id, primary_source_id,
      kyc_required, funding_raised_usd,
      estimated_value_usd_min, estimated_value_usd_max, social_score,
      project_url, twitter_url, discord_url,
      primary_cta_visit_code,
      started_at, snapshot_date, end_date
    ) VALUES (
      ${esc(a.slug)}, ${esc(a.name)}, ${esc(a.token_symbol)}, ${esc(a.logo_url)}, ${esc(a.short_description)},
      ${esc(a.description_md)}, ${esc(a.eligibility_md)}, ${esc(a.how_to_claim_md)},
      ${esc(a.status)},
      (SELECT id FROM chains WHERE slug = ${esc(a.chain)} LIMIT 1),
      (SELECT id FROM categories WHERE slug = ${esc(a.category)} LIMIT 1),
      (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1),
      ${a.kyc_required ? 1 : 0}, ${esc(a.funding_raised_usd)},
      ${esc(a.estimated_value_usd_min)}, ${esc(a.estimated_value_usd_max)}, ${esc(a.social_score)},
      ${esc(a.project_url)}, ${esc(a.twitter_url)}, ${esc(a.discord_url)},
      ${esc(code)},
      ${esc(a.started_at)}, ${esc(a.snapshot_date)}, ${esc(a.end_date)}
    ) ON DUPLICATE KEY UPDATE
      name=VALUES(name), token_symbol=VALUES(token_symbol), short_description=VALUES(short_description),
      description_md=VALUES(description_md), eligibility_md=VALUES(eligibility_md), how_to_claim_md=VALUES(how_to_claim_md),
      status=VALUES(status), chain_id=VALUES(chain_id), category_id=VALUES(category_id),
      kyc_required=VALUES(kyc_required), funding_raised_usd=VALUES(funding_raised_usd),
      estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max),
      social_score=VALUES(social_score),
      project_url=VALUES(project_url), twitter_url=VALUES(twitter_url), discord_url=VALUES(discord_url),
      primary_cta_visit_code=VALUES(primary_cta_visit_code),
      started_at=VALUES(started_at), snapshot_date=VALUES(snapshot_date), end_date=VALUES(end_date);`,
  );

  if (a.project_url) {
    chunks.push(
      `INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES (${esc(code)}, ${esc(a.project_url)}, (SELECT id FROM airdrops WHERE slug = ${esc(a.slug)} LIMIT 1), 'primary') ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), airdrop_id=VALUES(airdrop_id);`,
    );
  }

  // Reset FAQs then insert
  chunks.push(`DELETE FROM faqs WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = ${esc(a.slug)} LIMIT 1);`);
  for (let i = 0; i < a.faqs.length; i++) {
    const f = a.faqs[i];
    chunks.push(
      `INSERT INTO faqs (airdrop_id, position, question, answer_md) VALUES ((SELECT id FROM airdrops WHERE slug = ${esc(a.slug)} LIMIT 1), ${i}, ${esc(f.question)}, ${esc(f.answer_md)});`,
    );
  }
}
chunks.push("");

// guides
if (fs.existsSync(path.join(SEEDS_DIR, "guides.json"))) {
  const guides = readJson<GuideSeed[]>("guides.json");
  chunks.push("-- guides");
  for (const g of guides) {
    chunks.push(
      `INSERT INTO guides (slug, title, excerpt, body_md, published_at) VALUES (${esc(g.slug)}, ${esc(g.title)}, ${esc(g.excerpt)}, ${esc(g.body_md)}, ${esc(g.published_at)}) ON DUPLICATE KEY UPDATE title=VALUES(title), excerpt=VALUES(excerpt), body_md=VALUES(body_md), published_at=VALUES(published_at);`,
    );
  }
  chunks.push("");
}

// visit_codes (exchange affiliates + tool links)
if (fs.existsSync(path.join(SEEDS_DIR, "visit_codes.json"))) {
  const codes = readJson<CodeSeed[]>("visit_codes.json");
  chunks.push("-- visit_codes (exchange + tool affiliate stubs)");
  for (const c of codes) {
    chunks.push(
      `INSERT INTO visit_codes (code, target_url, airdrop_id, source_label) VALUES (${esc(c.code)}, ${esc(c.target_url)}, NULL, ${esc(c.source_label)}) ON DUPLICATE KEY UPDATE target_url=VALUES(target_url), source_label=VALUES(source_label);`,
    );
  }
  chunks.push("");
}

// known_airdrop_contracts
if (fs.existsSync(path.join(SEEDS_DIR, "known_contracts.json"))) {
  interface KnownContractSeed {
    airdrop_slug: string;
    airdrop_meta?: {
      name: string; token_symbol: string | null; status: string;
      chain: string; category: string; kyc_required: boolean;
      funding_raised_usd: number | null;
      estimated_value_usd_min: number | null; estimated_value_usd_max: number | null;
      social_score: number | null;
      short_description: string | null;
      project_url: string | null;
      started_at: string | null; end_date: string | null;
    };
    chain_slug: string; contract_addr: string; method: string;
    snapshot_block: number | null; claim_url: string | null; notes: string | null;
  }
  const known = readJson<KnownContractSeed[]>("known_contracts.json");
  chunks.push("-- known_airdrop_contracts (with bootstrap airdrops for /check demos)");
  for (const k of known) {
    if (k.airdrop_meta) {
      const m = k.airdrop_meta;
      chunks.push(
        `INSERT INTO airdrops (slug, name, token_symbol, short_description, status, chain_id, category_id, primary_source_id, kyc_required, funding_raised_usd, estimated_value_usd_min, estimated_value_usd_max, social_score, project_url, started_at, end_date) VALUES (${esc(k.airdrop_slug)}, ${esc(m.name)}, ${esc(m.token_symbol)}, ${esc(m.short_description)}, ${esc(m.status)}, (SELECT id FROM chains WHERE slug = ${esc(m.chain)} LIMIT 1), (SELECT id FROM categories WHERE slug = ${esc(m.category)} LIMIT 1), (SELECT id FROM sources WHERE slug = 'editorial' LIMIT 1), ${m.kyc_required ? 1 : 0}, ${esc(m.funding_raised_usd)}, ${esc(m.estimated_value_usd_min)}, ${esc(m.estimated_value_usd_max)}, ${esc(m.social_score)}, ${esc(m.project_url)}, ${esc(m.started_at)}, ${esc(m.end_date)}) ON DUPLICATE KEY UPDATE short_description=COALESCE(VALUES(short_description), short_description), status=VALUES(status), estimated_value_usd_min=VALUES(estimated_value_usd_min), estimated_value_usd_max=VALUES(estimated_value_usd_max);`,
      );
    }
    chunks.push(
      `DELETE FROM known_airdrop_contracts WHERE airdrop_id = (SELECT id FROM airdrops WHERE slug = ${esc(k.airdrop_slug)} LIMIT 1) AND chain_id = (SELECT id FROM chains WHERE slug = ${esc(k.chain_slug)} LIMIT 1) AND LOWER(contract_addr) = LOWER(${esc(k.contract_addr)});`,
    );
    chunks.push(
      `INSERT INTO known_airdrop_contracts (airdrop_id, chain_id, contract_addr, method, snapshot_block, claim_url, notes) VALUES ((SELECT id FROM airdrops WHERE slug = ${esc(k.airdrop_slug)} LIMIT 1), (SELECT id FROM chains WHERE slug = ${esc(k.chain_slug)} LIMIT 1), ${esc(k.contract_addr)}, ${esc(k.method)}, ${esc(k.snapshot_block)}, ${esc(k.claim_url)}, ${esc(k.notes)});`,
    );
  }
  chunks.push("");
}

fs.writeFileSync(OUT, chunks.join("\n") + "\n");
const size = fs.statSync(OUT).size;
console.log(`✓ Wrote ${OUT} (${(size / 1024).toFixed(1)} KB, ${chunks.filter((c) => c.startsWith("INSERT") || c.startsWith("DELETE")).length} statements)`);
